#
# Makefile rules for the crypting package
#
KEXT_NAME = crypting
KEXT_SOURCES = src/crypting.c

# include shared GAP package build system
GAPPATH = /private/var/tmp/sage-10.8-current/local/lib/gap/
include Makefile.gappkg
