ê&
"com.apple.siri.asr.dictation.en_GB&
"com.apple.siri.asr.dictation.de_DE&
"com.apple.siri.asr.dictation.ja_JP&
"com.apple.siri.asr.dictation.tr_TR&
"com.apple.siri.asr.dictation.en_IN'
#com.apple.siri.asr.dictation.yue_CN&
"com.apple.siri.asr.dictation.en_AU&
"com.apple.siri.asr.dictation.ar_SA&
"com.apple.siri.asr.dictation.es_MX&
"com.apple.siri.asr.dictation.fr_FR&
"com.apple.siri.asr.dictation.es_US&
"com.apple.siri.asr.dictation.zh_CN&
"com.apple.siri.asr.dictation.en_CA&
"com.apple.siri.asr.dictation.pt_BR&
"com.apple.siri.asr.dictation.ko_KR&
"com.apple.siri.asr.dictation.ru_RU&
"com.apple.siri.asr.dictation.it_IT&
"com.apple.siri.asr.dictation.zh_HK&
"com.apple.siri.asr.dictation.en_US&
"com.apple.siri.asr.dictation.es_ES