#\DeclareLyXModule[hereapplies.sty]{Here Applies}
#\DeclareCategory{Label and References}
#DescriptionBegin
#A module for for referencing groups of pages that share something in common.
#See the hereapplies.sty LaTeX package for more information.
#DescriptionEnd
#Author: madmurphy

Format 66

AddToPreamble
	\usepackage{hereapplies}
EndPreamble

InsetLayout "Flex:Here applies"
	LyXType			custom
	Decoration		Classic
	Font
		Family			Typewriter
		Color			black
		Size			Small
	EndFont
	LabelFont
		Family			Serif
		Color			teal
		Size			Small
	EndFont
	LabelString		"Here applies"
	LatexType		command
	LatexName		hereapplies
	Requires		hereapplies
	NoInsetLayout		true
	MultiPar		false
	CustomPars		false
	ForcePlain		true
	PassThru		false
	ParbreakIsNewline	true
	FreeSpacing		false
	ForceLTR		true
	BgColor			lightgray
	Argument 1
		Decoration		Classic
		Font
			Color			blue
		EndFont
		LabelString		"Label"
		MenuString		"Name of the label"
		Tooltip			"A string that will become the label for this point of the document (which can be referenced with \ref, \pageref, etc.)"
		Mandatory		0
	EndArgument
End

InsetLayout "Flex:Here applies*"
	LyXType			custom
	Decoration		Classic
	Font
		Family			Typewriter
		Color			black
		Size			Small
	EndFont
	LabelFont
		Family			Serif
		Color			teal
		Size			Small
	EndFont
	LabelString		"Here applies*"
	LatexType		command
	LatexName		hereapplies*
	Requires		hereapplies
	NoInsetLayout		true
	MultiPar		false
	CustomPars		false
	ForcePlain		true
	PassThru		false
	ParbreakIsNewline	true
	FreeSpacing		false
	ForceLTR		true
	BgColor			lightgray
	Argument 1
		Decoration		Classic
		Font
			Color			blue
		EndFont
		LabelString		"Label"
		MenuString		"Name of the label"
		Tooltip			"A string that will become the label for this point of the document (which can be referenced with \ref, \pageref, etc.)"
		Mandatory		0
	EndArgument
End

InsetLayout "Flex:Where applies"
	LyXType			custom
	Decoration		Classic
	Font
		Family			Typewriter
		Color			black
		Size			Small
	EndFont
	LabelFont
		Family			Serif
		Color			purple
		Size			Small
	EndFont
	LabelString		"Where applies"
	LatexType		command
	LatexName		whereapplies
	Requires		hereapplies
	NoInsetLayout		true
	MultiPar		false
	CustomPars		false
	ForcePlain		true
	PassThru		false
	ParbreakIsNewline	true
	FreeSpacing		false
	ForceLTR		true
	BgColor			lightgray
End

InsetLayout "Flex:Where applies*"
	LyXType			custom
	Decoration		Classic
	Font
		Family			Typewriter
		Color			black
		Size			Small
	EndFont
	LabelFont
		Family			Serif
		Color			purple
		Size			Small
	EndFont
	LabelString		"Where applies*"
	LatexType		command
	LatexName		whereapplies*
	Requires		hereapplies
	NoInsetLayout		true
	MultiPar		false
	CustomPars		false
	ForcePlain		true
	PassThru		false
	ParbreakIsNewline	true
	FreeSpacing		false
	ForceLTR		true
	BgColor			lightgray
End

