loaded_h_0(function(_){var window=this;
_.Ujc=_.y("eX5ure",[_.Cr]);
_.v("eX5ure");
var Vjc=class extends _.Cs{static Ta(){return{service:{Ub:_.Wu}}}constructor(a){super(a.Oa);this.parentElement=null;this.root=this.getRoot().el();this.id=this.getRoot().el().getAttribute("data-id");this.Ca=this.getRoot().el().hasAttribute("data-dc");this.Da=this.getRoot().el().hasAttribute("data-dw");this.oa=_.ji(this.getRoot().getData("backDisabled"),!1);this.Ub=a.service.Ub;this.registerContent()}Ba(){return this.root}Sb(){}registerContent(){this.trigger("jxvro",{controller:this})}Ea(a){a=a.ub.el();
this.trigger("dBhwS",{triggerElement:a})}cId(a){this.parentElement=a}getId(){return this.id}isDefault(){return this.Ca}hide(){_.Bn(this.root,!1)}JKc(a){this.hide();_.We(this.root)&&_.Zp(_.aq(this.Ub.oa(),this.root,2),a).log()}show(a){_.jn(this.root,{display:"block"});var b=this.Ya("LBJcic").el(),c=this.Ya("X0x7he").el();(b||this.oa)&&c&&(!this.oa&&b&&(a?_.jn(b,{display:"inline-block"}):_.Bn(b,!1)),b=this.Ya("vDg59d").el(),this.Da?(a=a?220:248,b&&(a-=48),_.jn(c,"width",`${a}px`)):b&&_.jn(c,"width",
`calc(100% - ${48+(a?28:0)}px)`))}U_b(a,b){this.show(a);_.We(this.root)&&_.Zp(_.aq(this.Ub.oa(),this.root,1),b).log()}qCc(a){var b=a.event.target,c,d,e=(d=(c=a.data)==null?void 0:c.contentId)!=null?d:b.getAttribute("data-id");this.parentElement&&this.ud(_.cy,this.parentElement,_.Vo).then(f=>f.Ha(e,b))}Aa(a){var b=a.ub.el();this.parentElement&&this.ud(_.cy,this.parentElement,_.Vo).then(c=>{if(c.Ca.length>0){c.Aa.JKc(b);let d=c.Ca.pop(),e=c.Ca.length>0;c.Aa=d;d.U_b(e,b)}})}};
Vjc.prototype.$wa$iO11jf=function(){return this.Aa};Vjc.prototype.$wa$uOhSee=function(){return this.qCc};Vjc.prototype.$wa$ZYIfFd=function(){return this.hide};Vjc.prototype.$wa$paynGb=function(){return this.isDefault};Vjc.prototype.$wa$pTuYge=function(){return this.getId};Vjc.prototype.$wa$QQtcRd=function(){return this.Ea};Vjc.prototype.$wa$CHHOAf=function(){return this.registerContent};Vjc.prototype.$wa$k4Iseb=function(){return this.Sb};Vjc.prototype.$wa$xdy80=function(){return this.Ba};
_.Es(_.Ujc,Vjc);
_.x();
_.v("SeHsMb");
var F5p,G5p,H5p,K5p,J5p,I5p;_.E5p=function(){var a=new _.TSd;return _.Yh(a,1,1)};
F5p=function(a){var b=a.Ja("jUiHZc").el(),c=a.Ja("l0BSve").el();switch(a.oa){case 2:b.setAttribute("selected","");c.removeAttribute("selected");break;case 1:b.removeAttribute("selected");c.setAttribute("selected","");break;default:b.removeAttribute("selected"),c.removeAttribute("selected")}b.setAttribute("aria-pressed",String(b.getAttribute("selected")!==null));c.setAttribute("aria-pressed",String(c.getAttribute("selected")!==null))};
G5p=function(a,b){var c=_.MVd(a.getRoot());c.isEmpty()?a.notify("aIJAdf",b):_.Yg(c.el(),"aIJAdf",b)};H5p=function(a){return _.ci(a.Un,18)===5||_.ci(a.Un,18)===17||_.ci(a.Un,18)===18||_.ci(a.Un,18)===23||_.ci(a.Un,18)===30};
K5p=async function(a){var b=(0,_.Wf)(),c=b();b=b(1);try{let f=a.Ca();if(f){var d=f.getAttribute("data-dt")==="true",e=a.rc||d;switch(a.oa){case 1:e||(a.Ba=(0,_.po)(a.yb.bind(a),6E3));b(await c(a.Oe.open(f,_.wv(a.Gb,()=>{a.Ba&&((0,_.qo)(a.Ba),a.Ba=null);a.Ha();return!0}))));I5p(a,f,a.Ja("l0BSve").el());_.Rv([new _.ko(f,"show")]);J5p(a,f);break;case 2:e||(a.Ba=(0,_.po)(a.yb.bind(a),6E3));b(await c(a.Oe.open(f,_.wv(a.Gb,()=>{a.Ba&&((0,_.qo)(a.Ba),a.Ba=null);a.Ha();return!0}))));I5p(a,f,a.Ja("jUiHZc").el());
_.Rv([new _.ko(f,"show")]);J5p(a,f);break;default:a.Oe.close(f),(0,_.qo)(a.Ba),a.Ba=null,_.Rv([new _.ko(f,"hide")])}_.fr()}}finally{c()}};J5p=function(a,b){b&&(b=b.querySelector('[jsname="SR5kYd"]'))&&(a.cG||(a.cG=new _.wkc(b)),requestAnimationFrame(()=>{var c,d;(c=a.cG)==null||(d=_.tkc(c,0))==null||d.focus();var e;(e=a.cG)==null||_.ukc(e)}))};I5p=function(a,b,c){requestAnimationFrame(()=>{var d=a.Bb(b,c);d&&(b.style.left=`${d.left}px`,b.style.top=`${d.top}px`)})};
_.L5p=function(a){switch(a){case 1:return 40;case 2:return 41;default:return 42}};
_.M5p=class extends _.Cs{static Ta(){return{service:{overlay:_.rv},jsdata:{Un:_.w5p}}}constructor(a){super(a.Oa);this.zc=_.rIa?100:0;this.cG=void 0;this.oa=0;this.Ea=17;this.Da=18;this.kb=this.Za=0;this.Oe=a.service.overlay;this.Hd=this.getData("ozi").Ob();this.Gb=this.Sa();this.Ba=null;this.Un=a.jsdata.Un;this.Yc=_.ji(this.getData("pstp"),!0);this.Wc=_.ji(this.getData("ngtp"),!0);this.Oc=_.ji(this.getData("negsrvywotooltip"),!1);this.ld=_.ji(this.getData("possrvywotooltip"),!1);this.rc=_.ji(this.getData("dt"),
!1);(a=this.Ca())&&_.Yo(this,a);a=_.Cd(this.getData("rl"),0);this.Dc=a>0?_.Bs(this.Ma.bind(this),a):this.Ma.bind(this);this.Jc=a>0?_.Bs(this.La.bind(this),a):this.La.bind(this)}Pa(){this.Dc()}Ma(){this.oa=this.oa===1?0:1;F5p(this);var a=this.Aa();G5p(this,a);H5p(this)||_.Sv(this.Ja("l0BSve").el());if(this.Yc){if(a=this.Ca())_.Yg(a,"HyEYFc",this.oa),_.Yg(a,"nC1BTb",this.Ea),K5p(this)}else this.ld&&this.oa===1&&(a=_.eH(_.cH(new _.QG,_.Aj(this.Un,17)),this.Ea),_.Yg(document,"kPzEO",a))}Na(){this.Jc()}La(){this.oa=
this.oa===2?0:2;F5p(this);var a=this.Aa();G5p(this,a);H5p(this)||_.Sv(this.Ja("jUiHZc").el());if(this.Wc){if(a=this.Ca())_.Yg(a,"HyEYFc",this.oa),_.Yg(a,"DouR6c",this.Da),K5p(this)}else this.Oc&&this.oa===2&&(a=_.eH(_.cH(new _.QG,_.Aj(this.Un,17)),this.Da),_.Yg(document,"kPzEO",a))}Ha(){this.cG&&_.vkc(this.cG)}Sa(){var a=new _.Dv;_.Cv(a,1);_.zv(a,!0);var b=document.body.querySelector('[jsname="vVGdvd"]');b&&b.contains(this.getRoot().el())||this.Hd||_.KUb(a,128);return a}Bb(a,b){var c=a.getBoundingClientRect();
c.width>0&&(this.kb=c.width);c.height>0&&(this.Za=c.height);a=c.width||this.kb;var d=c.height||this.Za;b=b.getBoundingClientRect();var e=window.innerHeight;if(c&&b)return c=b.top+window.scrollY,{left:Math.max(b.left+a<window.innerWidth?b.left:b.right-a,0),top:b.bottom+d+10+this.zc<e?c+b.height+10:c-d-10}}yb(){var a=this.Ca();a&&(this.Oe.close(a),(0,_.qo)(this.Ba),this.Ba=null,_.fr())}Ca(){var a=Array.from(document.body.querySelectorAll('[jsname="pSHapd"]')).filter(b=>b.getAttribute("data-kpid")===
_.Aj(this.Un,17));return a.length===0?null:a[0]}};_.M5p.prototype.$wa$BbhDbd=function(){return this.Ca};_.M5p.prototype.$wa$UwrDXb=function(){return this.Sa};_.M5p.prototype.$wa$Se0Yg=function(){return this.Ha};_.M5p.prototype.$wa$icFFmd=function(){return this.La};_.M5p.prototype.$wa$XZ3FXe=function(){return this.Na};_.M5p.prototype.$wa$pQjEVb=function(){return this.Ma};_.M5p.prototype.$wa$OkLptf=function(){return this.Pa};
_.x();
_.N5p=_.xi("SeHsMb",[_.sr]);
_.yyr=_.y("LKcpDc",[_.UYo,_.N5p]);
_.v("LKcpDc");
var fft=function(a,b){b=_.Ma(eft(b),4);_.Sv(a,{data:{mfl:b}})},eft=_.Ob(_.AWb),gft={UNSPECIFIED:0,RWf:1,Nkf:2},hft=async function(a){var b=(0,_.Wf)(),c=b();b=b(1);try{a.ALa=b(await c(a.getModel(_.wyr)))}finally{c()}},ift=function(a){var b;(b=a.ALa)==null||b.Da(a.Ua)},kft=function(a,b){var c=(new _.oWb).setResponseType(Number(a.responseType)).setQuery(a.query);c=_.Yh(c,15,jft(a.Ua));switch(a.oa){case 2:_.Yh(c,1,2);break;case 1:_.Yh(c,1,1);break;default:_.Yh(c,1,0)}fft(b,c)},lft=function(a,b){a=a.getRoot().closest(_.aMi).hb();
if(!a)return[];var c=[];a.querySelectorAll(_.DU("fBMxqf")).forEach(d=>{(d=d.getAttribute("data-mfiui"))&&!b.includes(d)&&c.push(d)});return c},jft=function(a){switch(a){case 2:return 2;case 1:return 1;default:return 0}},mft=function(a){switch(a){case 9:return 1;case 11:return 2;case 2:return 3;case 1:return 4;case 8:return 5;case 7:return 6;case 6:return 7;case 43:return 8;case 70:return 10;case 23:return 9;case 18:return 11;default:return 0}},nft=class extends _.M5p{static Ta(){return{jsdata:{Un:_.w5p},
model:{Tv:_.WYo}}}constructor(a){super(a.Oa);this.responseType=_.qm(this.getData("rt"));this.Ua=this.getData("tl").Ah(gft);this.query=_.qm(this.getData("q"));this.ALa=null;this.Un=a.jsdata.Un;this.Tv=a.model.Tv;var b=this.Ja("jGsbz"),c=this.Ja("KTP9Gb");this.uDa(hft(this).then(()=>{var d;(d=this.ALa)==null||d.Ma(g=>{this.Un=g});var e;(e=this.ALa)==null||e.Ha(g=>{g&&(b.empty().append(g.cloneNode(!0)),_.ewa(document).dirtySubtree(b.el()))});var f;(f=this.ALa)==null||f.Ea(g=>{if(g){var h=new _.UVd,k=
new _.OG,l=new _.Fqg;g=_.Yh(l,40,g);k=_.Fb(k,_.Fqg,4,g);h=_.Fb(h,_.OG,2,k);c.setData("ffd",h.serialize())}})}))}Ma(){ift(this);super.Ma();var a;(a=this.ALa)==null||a.Ba(!0);kft(this,this.Ja("l0BSve").el())}La(){ift(this);super.La();var a;(a=this.ALa)==null||a.Ba(!0);kft(this,this.Ja("jUiHZc").el())}Ha(){super.Ha();var a;(a=this.ALa)==null||a.Ba(!1)}Aa(){var a=_.Cqg(_.E5p());a=_.Yh(a,4,4);var b=_.L5p(this.oa),c=_.L5p(this.oa),d,e;var f=(e=(d=this.getRoot().el().closest(_.cMi))==null?void 0:d.getAttribute("eid"))!=
null?e:null;var g,h,k;d=(k=(g=this.Un)==null?void 0:(h=g.Kz())==null?void 0:_.Gqg(h))!=null?k:new _.Fqg;g=_.qm(this.getData("mstk"));if(!g){var l;g=(l=this.Tv.getMagiState())==null?void 0:l.stateToken}l=_.eh(d,1,g);c=_.zk(l,2,[c]);f=_.eh(c,23,f);c=[..._.Kj(f,14,_.qh())];c=lft(this,c);c=_.nva(f,14,c);_.Yh(c,40,this.Ua);c=this.getRoot().closest(_.pRa("ved")).getData("ved");b=_.wsg(_.vsg(_.usg(_.Bsg(_.Asg(new _.Esg,5297367),"opentext"),b),this.query),"/m/01dpt8").setAttribute("MagiThumbsFeedback");c=
_.qm(c);b=_.eh(b,7,c);b=_.ysg(_.xsg(b,[]),4589);a=_.Dqg(new _.OG,a);a=_.Fb(a,_.Fqg,4,f);a=_.zsg(b,a);var n,q;b=(q=(n=this.Un)==null?void 0:_.Yi(n,13,void 0,void 0,_.nb))!=null?q:_.Mba();b.isEmpty()||_.qk(a,15,b);var r;((r=this.Un)==null?0:_.Mk(r,12))&&_.Dsg(a,_.ci(this.Un,12));_.Csg(a,_.Aj(this.Un,17));return a}Va(a){var b=this.Ya("dn2ejb").el();if(b){var c,d,e;if((c=a.data)!=null&&_.rh(c,16)&&((d=a.data)==null?void 0:d.Ba())===((e=this.Un)==null?void 0:_.Aj(e,17))){a=[mft(a.data.Da()||0)];c=(new _.oWb).setResponseType(Number(this.responseType)).setQuery(this.query);
c=_.zk(c,6,a);a=_.zk(c,10,a);a=_.Yh(a,15,jft(this.Ua));switch(this.oa){case 2:_.Yh(a,1,2);break;case 1:_.Yh(a,1,1)}fft(b,a)}}}};nft.prototype.$wa$a3NWR=function(){return this.Va};nft.prototype.$wa$GqqcTb=function(){return this.Aa};nft.prototype.$wa$Se0Yg=function(){return this.Ha};nft.prototype.$wa$icFFmd=function(){return this.La};nft.prototype.$wa$pQjEVb=function(){return this.Ma};_.Es(_.yyr,nft);
_.x();
_.xyr=_.y("BzlSce",[_.wyr]);
_.v("BzlSce");
var oft=class extends _.m{constructor(a){super(a)}};oft.prototype.rb="GBhlFe";_.Es(_.xyr,class extends _.Cs{static Ta(){return{model:{ALa:_.dft},jsdata:{bvb:oft}}}constructor(a){super(a.Oa);var b=a.model.ALa;a=_.p(a.jsdata.bvb,_.w5p,1);b.bvb.value={Un:a};a=this.Ya("pSHapd");a.isEmpty()||b.l$(a.hb())}});
_.x();
});
// Google Inc.
