%% ***********************************************************************
%%            Copyright 2024 by M.Y. XIA <xiamyphys@gmail.com>           *
%%                                                                       *
%%    This work may be distributed and/or modified under the conditions  *
%%    of the LaTeX Project Public License                                *
%%                                                                       *
%%               http://www.latex-project.org/lppl.txt                   *
%%                                                                       *
%%    either version 1.3c of this license or any later version.          *
%%                                                                       *
%%    This work has the LPPL maintenance status `obsoleted'.             *
%%    This work has the LPPL maintenance status `obsoleted'.             *
%%    This work has the LPPL maintenance status `obsoleted'.             *
%% ***********************************************************************
\ProvidesExplClass {litebook} {2024/11/26} {0.2b}
  {Now replaced by the whatsnote class}

\msg_new:nnn { litebook } { Obsolete~LaTeX~Package }
  { The~litebook~class~is~now~obsoleted.~
    Please~load~the~`whatsnote'~class~instead,~or~
    access~the~'obsolete~packages'~dictionary~on~CTAN. }
\msg_error:nn { litebook } { Obsolete~LaTeX~Package }

\LoadClass{minimal}

\endinput