(function(g){var window=this;'use strict';var Yt=function(F,J){g.U.call(this,{X:"button",Dv:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],L:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},j:[{X:"svg",L:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},j:[{X:"g",L:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},j:[{X:"g",L:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
j:[{X:"path",L:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.G=F;this.listen("click",this.onClick,this);this.updateValue("title",g.NZ(F,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.iy(J.W1(),this.element))},fF8=function(F){g.U.call(this,
{X:"div",
K:"ytp-miniplayer-ui"});this.W=!1;this.player=F;this.B(F,"minimized",this.Kv);this.B(F,"onStateChange",this.XhG);this.B(F,"documentpictureinpicturechange",this.gl_)},W6z=function(F,J){g.qr(F.player.getRootNode(),"ytp-player-minimized",J)},d65=function(F){g.GN.call(this,F);
this.U=new g.s5(this);this.C=new fF8(this.player);this.C.hide();g.Pp(this.player,this.C.element,4);F.isMinimized()&&(this.load(),g.qr(F.getRootNode(),"ytp-player-minimized",!0))};
g.z(Yt,g.U);Yt.prototype.onClick=function(){this.G.jE("onExpandMiniplayer")};g.z(fF8,g.U);g.A=fF8.prototype;
g.A.show=function(){this.C=new g.n8(this.jr,null,this);this.C.start();if(!this.W){this.tooltip=new g.s3(this.player,this);g.k(this,this.tooltip);g.Pp(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Fd=new g.I9(this.player);g.k(this,this.Fd);this.progressBar=new g.xr(this.player,this);g.k(this,this.progressBar);g.Pp(this.player,this.progressBar.element,4);this.U=new g.U({X:"div",K:"ytp-miniplayer-scrim"});g.k(this,this.U);this.U.Az(this.element);this.B(this.U.element,"click",this.xP);
var F=new g.U({X:"button",Dv:["ytp-miniplayer-close-button","ytp-button"],L:{"aria-label":"Close"},j:[g.iA()]});g.k(this,F);F.Az(this.U.element);this.B(F.element,"click",this.aR);F=new Yt(this.player,this);g.k(this,F);F.Az(this.U.element);this.T=new g.U({X:"div",K:"ytp-miniplayer-controls"});g.k(this,this.T);this.T.Az(this.U.element);this.B(this.T.element,"click",this.xP);var J=new g.U({X:"div",K:"ytp-miniplayer-button-container"});g.k(this,J);J.Az(this.T.element);F=new g.U({X:"div",K:"ytp-miniplayer-play-button-container"});
g.k(this,F);F.Az(this.T.element);var b=new g.U({X:"div",K:"ytp-miniplayer-button-container"});g.k(this,b);b.Az(this.T.element);this.Y=new g.Ob(this.player,this,!1);g.k(this,this.Y);this.Y.Az(J.element);J=new g.kr(this.player,this);g.k(this,J);J.Az(F.element);this.nextButton=new g.Ob(this.player,this,!0);g.k(this,this.nextButton);this.nextButton.Az(b.element);this.V=new g.E3(this.player,this,0);g.k(this,this.V);this.V.Az(this.U.element);this.Z=new g.U({X:"div",K:"ytp-miniplayer-buttons"});g.k(this,
this.Z);g.Pp(this.player,this.Z.element,4);F=new g.U({X:"button",Dv:["ytp-miniplayer-close-button","ytp-button"],L:{"aria-label":"Close"},j:[g.iA()]});g.k(this,F);F.Az(this.Z.element);this.B(F.element,"click",this.aR);F=new g.U({X:"button",Dv:["ytp-miniplayer-replay-button","ytp-button"],L:{"aria-label":"Close"},j:[g.dV()]});g.k(this,F);F.Az(this.Z.element);this.B(F.element,"click",this.ief);F=new Yt(this.player,this);g.k(this,F);F.Az(this.Z.element);this.B(this.player,"presentingplayerstatechange",
this.nC);this.B(this.player,"appresize",this.mO);this.B(this.player,"fullscreentoggled",this.mO);this.mO();this.W=!0}this.player.getPlayerState()!==0&&g.U.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.A.hide=function(){this.C&&(this.C.dispose(),this.C=void 0);g.U.prototype.hide.call(this);this.player.isMinimized()||(this.W&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.A.X_=function(){this.C&&(this.C.dispose(),this.C=void 0);g.U.prototype.X_.call(this)};
g.A.aR=function(){this.player.S("kevlar_watch_while_v2")||this.player.stopVideo();this.player.jE("onCloseMiniplayer")};
g.A.ief=function(){this.player.playVideo()};
g.A.xP=function(F){if(F.target===this.U.element||F.target===this.T.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.A.Kv=function(){W6z(this,this.player.isMinimized())};
g.A.gl_=function(){W6z(this,this.player.JN());g.qr(this.player.getRootNode(),"ytp-player-document-picture-in-picture",this.player.JN())};
g.A.aP=function(){this.progressBar.Q6();this.V.Q6()};
g.A.jr=function(){this.aP();this.C&&this.C.start()};
g.A.nC=function(F){g.x(F.state,32)&&this.tooltip.hide()};
g.A.mO=function(){var F=this.player.mG().getPlayerSize().width;g.kra(this.progressBar,0,F,!1);g.nn(this.progressBar)};
g.A.XhG=function(F){this.player.isMinimized()&&(F===0?this.hide():this.show())};
g.A.W1=function(){return this.tooltip};
g.A.kU=function(F,J,b,I,u){var w=0,M=0,q=0,v=g.fL(F);I=J&&(g.I3(J,"ytp-prev-button")||g.I3(J,"ytp-next-button"));if(J){b=g.I3(J,"ytp-play-button");var a=g.I3(J,"ytp-miniplayer-expand-watch-page-button");I?w=q=12:b?(J=g.NB(J,this.element),q=J.x,w=J.y-12):a&&(q=g.I3(J,"ytp-miniplayer-button-top-left"),w=g.NB(J,this.element),J=g.fL(J),q?(q=8,w=w.y+40):(q=w.x-v.width+J.width,w=w.y-20))}else q=b-v.width/2,M=25+(u||0);J=this.player.mG().getPlayerSize();u=w+(u||0);v=g.AD(q,0,J.width-v.width-12);u?(F.style.top=
u+"px",F.style.bottom=""):(F.style.top="",F.style.bottom=M+"px");F.style.left=v+"px";M=g.I3(F,"ytp-preview");F.style.visibility=I&&M&&J.height<225?"hidden":""};g.z(d65,g.GN);g.A=d65.prototype;g.A.onVideoDataChange=function(){if(this.player.getVideoData()){var F=this.player.getVideoAspectRatio(),J=16/9;F=F>J+.1||F<J-.1;g.qr(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",F)}};
g.A.create=function(){g.GN.prototype.create.call(this);this.U.B(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.A.u7=function(){return!1};
g.A.load=function(){this.player.hideControls();this.C.show()};
g.A.unload=function(){this.player.showControls();this.C.hide()};g.jn("miniplayer",d65);})(_yt_player);
