.\" Manpage for texaccents
.\" Contact guido.milanese@unicatt.it to correct errors or typos.
.TH man 8 "17th September 2022" "1.0.1" "texaccents man page" 
.SH NAME
texaccents - Converts legacy (La)TeX accents and ligatures to Unicode
.SH DESCRIPTION
A Snobol script. Example: \={a} ('a' with macron) will be converted to ā.
.SH OPTIONS
No options besides --help and --version.
.SH AUTHOR
Guido Milanese (guido.milanese@unicatt.it)
.SH BUGS
Please send bug reports or other correspondence to guido.milanese@unicatt.it
.SH SEE ALSO
CTAN page of the package: https://www.ctan.org/pkg/texaccents
