'\" t
.\"     Title: tikztosvg
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2021-08-19
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "TIKZTOSVG" "1" "2021-08-19" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
tikztosvg \- Render TikZ diagrams to SVG.
.SH "SYNOPSIS"
.sp
\fBtikztosvg\fP [\fIOPTION\fP]... \fIINPUT_PATH\fP
.SH "DESCRIPTION"
.sp
The tikztosvg(1) command renders TikZ diagrams to SVG.
.sp
If \fIINPUT_PATH\fP is set to \fI\-\fP the input will be read from stdin.
.SH "OPTIONS"
.sp
\fB\-o, \-\-output\fP=\fIOUTPUT_PATH\fP
.RS 4
Write output to file \fIOUTPUT_PATH\fP.
If set to \fI\-\fP the output will be written to stdout.
Defaults to the base name of the input file suffixed with the \fI.svg\fP
extension. The file is resolved relative to the working directory.
.RE
.sp
\fB\-p, \-\-package\fP=+\fIPACKAGE\fP
.RS 4
Include \fI\(rsusepackage{PACKAGE}\fP when rendering the diagram. The tikz, tikz\-cd,
pgfplots, amsmath and amssymb packages are always included by default.
.RE
.sp
\fB\-l, \-\-library\fP=+_LIBRARY
.RS 4
Include \fI\(rsusetikzlibrary{LIBRARY}\fP when rendering the diagram.
.RE
.sp
\fB\-q, \-\-quiet\fP
.RS 4
Silence application log messages and script warnings.
.RE
.sp
\fB\-\-lualatex\fP
.RS 4
Use LuaTeX as the TeX engine. LuaTeX is already the
default, so this option doesn\(cqt really do much.
.RE
.sp
\fB\-\-xelatex\fP
.RS 4
Use XeTeX as the TeX engine.
.RE
.sp
\fB\-\-pdflatex\fP
.RS 4
Use pdfTeX as the TeX engine.
.RE
.sp
\fB\-h, \-\-help\fP
.RS 4
Print a help message.
.RE
.sp
\fB\-v, \-\-version\fP
.RS 4
Prints version information.
.RE
.SH "ENVIRONMENT"
.sp
\fBtikztosvg\fP requires XeTeX and pdf2svg to be installed. Make sure
any additional LaTeX packages are installed before using them in a diagram.
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB1\fP
.RS 4
Failure (syntax or usage error; configuration error).
.RE
.sp
\fB[n]\fP
.RS 4
Failure (document processing failure).
.RE
.SH "AUTHORS"
.sp
\fBtikztosvg\fP was written by Pablo \c
.MTO "pablo\-escobar\(atriseup.net" "" "."
.sp
\fBpdf2svg\fP was written by David Barton \c
.MTO "davebarton\(atcityinthesky.co.uk" "" ""
and
Matthew Flaschen \c
.MTO "matthew.flaschen\(atgatech.edu" "" "."
.SH "RESOURCES"
.sp
Git source repository on sourcehut
.RS 4
.URL "https://git.sr.ht/~pablo\-pie/tikztosvg" "" ""
.RE
.sp
Bug tracker
.RS 4
.URL "https://todo.sr.ht/~pablo\-pie/tikztosvg" "" ""
.RE
.sp
CTAN package
.RS 4
.URL "https://www.ctan.org/pkg/tikztosvg" "" ""
.RE
.sp
TeXLive
.RS 4
.URL "https://tug.org/texlive/" "" ""
.RE
.sp
LuaTeX
.RS 4
.URL "http://luatex.org/" "" ""
.RE
.sp
XeTeX
.RS 4
.URL "http://xetex.sourceforge.net/" "" ""
.RE
.sp
\fBpdfTeX\fP \c
.URL "https://www.tug.org/applications/pdftex/" "" ""
.SH "COPYING"
.sp
Copyright (C) 2021 Pablo.
Free use of this software is granted under the terms of the GPL\-3.0 License.