loaded_h_0(function(_){var window=this;
_.nRb=[2,4];
_.v("p3hmRc");
var pRb,rRb,yRb,wRb;_.sRb=function(){var a,b;oRb!=null||(oRb=Object.freeze({get enabled(){return oRb.Yta===-1||_.ji(pRb("iCzhFc"),!1)?!1:oRb.R_e.enabled||oRb.V2c.enabled||oRb.cMe.enabled},environment:pRb("HiPsbb").Bh(qRb,0),m4d:(a=_.qm(pRb("MUE6Ne")))!=null?a:void 0,Q1a:(b=_.qm(pRb("cfb2h")))!=null?b:void 0,Yta:_.Bd(pRb("yFnxrf"),-1),v$d:_.AJa(pRb("fPDxwd")).map(c=>_.Bd(c,0)).filter(c=>c>0),R_e:rRb("xwAfE",()=>"UUFaWc"),V2c:rRb("xnI9P",()=>"u4g7r"),cMe:rRb("AfY8Hf",()=>"hsFLT")}));return oRb};
pRb=function(a){var b=tRb(a);if(!b.Ob()&&_.da!==_.da.top)try{b=tRb(a,_.da.top)}catch(c){if(!(c instanceof DOMException&&c.name==="SecurityError")){if(c instanceof Error)throw c;throw Error("sf`"+c);}}return b};rRb=function(a,b){a=_.ji(pRb(a),!1);return{enabled:a,wmc:a?_.xm(pRb(b()),_.uRb).Vd():vRb()}};
yRb=function(a,b){var c=_.OVa();var d=[];var e;c=_.d$a(_.b$a(_.BLb(new _.f$a(a,c),_.CLb(new _.DLb,b.v$d)),(e=b.Q1a)!=null?e:""));d&&d.length>0&&wRb(c,d.map(h=>_.jb(h)));switch(a){case 1957:var f=3;break;case 2082:f=2;break;case 1884:f=1;break;case 2649:f=0}var g;return new xRb(c.build(),(g=b.m4d)!=null?g:"",f,b.environment)};wRb=function(a,b){a.Da=b};_.uRb=class extends _.m{constructor(a){super(a)}};var vRb=_.Jb(_.uRb);var qRb={Ojf:0,UHf:1,aSf:2,Q5e:3,Wtc:4};var oRb,tRb=_.zd;var xRb=class{constructor(a,b,c,d=0){this.transport=a;this.appName=b;this.oa=c;this.environment=d}},zRb=class{dispatch(){}flush(){}};_.ARb=class extends _.yo{constructor(){super();this.config=_.sRb();this.oa=this.config.enabled?yRb(this.config.Yta,this.config):new xRb(new zRb)}};_.hg(_.D$a,_.ARb);
_.x();
_.HRb=[2,3];_.IRb=[1,2];_.JRb=[3,4,5];
var ERb;_.DRb=function(a,b){return _.gk(a,2,b)};ERb=function(a,b){Number.isFinite(b)||(b=0);return _.DRb(a.setSeconds(Math.floor(b/1E3)),(b%1E3+1E3)%1E3*1E6)};_.FRb=function(a){var b=new _.mm;return ERb(b,a.getTime())};_.GRb=function(a){return ERb(new _.mm,a)};
_.v("pNBFbe");
var KRb=function(a){var b;return a.TAa+((b=a.Lo)!=null?b:0)},QRb=function(a,b,c,d){a=LRb((new MRb).Uc(a),d);d=_.oj(a,NRb,5,_.JRb);d=_.nj(d,ORb,1);PRb(d,c).Je(b);return a},RRb=function(a){return _.CRb(new _.cs,a)},SRb=class extends _.m{constructor(a){super(a)}getUrl(){return _.u(this,3)}jd(){return _.rh(this,3)}Aa(a){_.eh(this,5,a)}Ca(a){_.Yh(this,8,a)}Da(a){_.eh(this,10,a)}Ba(a){_.Yh(this,11,a)}},TRb=class extends _.m{constructor(a){super(a)}},URb=class extends _.m{constructor(a){super(a)}getType(){return _.Ej(this,
1)}setType(a){return _.Yh(this,1,a)}Bf(){return _.Nk(this,1)}xf(){return _.ci(this,1)}getId(){return _.uFa(this,2,_.HRb)}Uc(a){return _.kj(this,2,_.HRb,_.bb(a))}Fh(){var a=_.$i(this,_.HRb,2);return _.Eda(_.Yi(this,a,void 0,void 0,_.cb))!=null}Kf(){return _.yFa(this,2,_.HRb)}},VRb=class extends _.m{constructor(a){super(a)}getStatus(){return _.Ej(this,2)}Om(){return _.Nk(this,2)}},WRb=class extends _.m{constructor(a){super(a)}},XRb=class extends _.m{constructor(a){super(a)}},PRb=function(a,b){return _.kk(a,
2,b)},YRb=function(a,b){_.Ffa(a,3,_.Dda,b,_.Eda)},ORb=class extends _.m{constructor(a){super(a)}getName(){return _.u(this,1)}Je(a){return _.eh(this,1,a)}hh(){return _.rh(this,1)}},NRb=class extends _.m{constructor(a){super(a)}},ZRb=function(a,b){_.Yh(a,7,b)},$Rb=class extends _.m{constructor(a){super(a)}setInterval(a){return _.Zh(this,9,a)}clearInterval(){return _.cf(this,9)}},aSb=class extends _.m{constructor(a){super(a)}},LRb=function(a,b){return _.Fb(a,_.cs,2,b)},bSb=function(a){var b=new aSb;
return _.sj(a,4,_.JRb,b)},MRb=class extends _.m{constructor(a){super(a)}getId(){return _.Cj(this,1)}Uc(a){return _.kk(this,1,a)}Fh(){return _.Fk(this,1)}Kf(){return _.Yi(this,1,void 0,void 0,_.cb)}},cSb=class extends _.m{constructor(a){super(a)}getId(){return _.Cj(this,1)}Uc(a){return _.nk(this,1,a)}Fh(){return _.Hk(this,1)}Kf(){return _.Yi(this,1,void 0,void 0,_.cb)}getName(){return _.u(this,2)}Je(a){return _.eh(this,2,a)}hh(){return _.rh(this,2)}getStartTime(){return _.p(this,_.mm,4)}xra(){return _.cf(this,
4)}getDuration(){return _.p(this,_.cs,11)}s5(){return _.cf(this,11)}Lja(){return _.pj(this,_.cs,11)}},dSb=new _.i0a,eSb=new _.i0a;var fSb=Symbol();var gSb=class extends _.m{constructor(a){super(a)}Aa(){return _.nj(this,SRb,5)}Ba(a){_.Fb(this,_.uRb,18,a)}};var hSb=new _.i0a;var iSb=new _.i0a,jSb=new _.i0a;var lSb=class{constructor(a,b){this.oa=a;this.wmc=b;a=this.Aa.bind(this);if(_.$za===void 0)throw Error("Id");if(_.$za)for(let [c,d]of _.$za)a(c,d);_.aAa.add(a);_.$za=void 0}Aa(a,b){if(a.l$.length!==1||a.l$[0].Lo!==0){var c=Number;var d=this.wmc;d=_.af(d,_.$i(d,_.nRb,2));a=(new kSb(a,b,c(d)/1E3)).La;c=new gSb;a=_.Fb(c,cSb,16,a);var e;for(var [,f]of b.entries())c=f,(d=c.get(hSb))&&d.Qed&&(b=a,d=d.Qed.getId(fSb),_.vk(b,19,d)),(b=c.get(eSb))&&(e=b);f=this.wmc;var g;if((g=e)==null?0:g.oa)g=new _.uRb,e=
_.FFa(g,2,_.nRb,e.Aa),f=_.Yh(e,3,2).Vd();e=this.oa;g=f;f=a.Aa();e.appName!==void 0&&f.Aa(e.appName);f.Ba(e.environment);e.oa&&f.Ca(e.oa);let h,k;(b=(h=_.Yb())==null?void 0:(k=h.Db)==null?void 0:_.Gna(k.La))&&f.Da(b);a.Ba(g);e.transport.dispatch(a);e.transport.flush()}}},nSb=function(a,b){var c=(0,_.Wf)(1),d=c(),e=c(1);return function*(){e();try{e(yield d(QRb(mSb(a,b.id),b.name,mSb(a,b.parentId),RRb(b.TAa))))}finally{d()}}()},oSb=function(a,b){var c=(0,_.Wf)(1),d=c(),e=c(1);return function*(){e();
try{let f=RRb(b.TAa),g=void 0,h;b.parentId===void 0?(g=a.Da++,h=0):h=mSb(a,b.parentId);if(!b.i1b&&b.parentId!==void 0){g=a.Da++;let r=a.Ca++;e(yield d(QRb(r,_.Zza(b.name,"APGx0e"),h,f)));h=r}let k=mSb(a,b.id),l=LRb((new MRb).Uc(k),f),n=_.oj(l,$Rb,3,_.JRb);g&&_.kk(n,2,g);PRb(_.nj(n,ORb,1),h).Je(b.name);let q=a.extras.get(b.id);if(q){let r=q.get(iSb);r&&ZRb(_.eh(n,6,r.oa),r.Aa);let t=q.get(jSb);if(t){let A=Array.from(t.oa,E=>mSb(a,E));YRb(_.nj(n,ORb,1),A)}}e(yield d(l));b.Lo!==void 0&&e(yield d(bSb(LRb((new MRb).Uc(k),
b.Lo===0?f:RRb(KRb(b))))))}finally{d()}}()},mSb=function(a,b){var c=a.oa[b];c===void 0&&(a.oa[b]=c=a.Ca++);return c},kSb=class{constructor(a,b,c){this.Ha=a;this.extras=b;this.Da=this.Ca=1;this.Ba=Number.POSITIVE_INFINITY;this.Aa=Number.NEGATIVE_INFINITY;this.Ea=Array(a.l$.length).fill(!1);this.oa=Array(a.l$.length);b=(new cSb).Uc(String(a.id));var d=_.GRb(a.startTimeMs);b=_.Fb(b,_.mm,4,d);d=_.nj(b,XRb,10);_.IFa(d,1,_.IRb,c);for(var e of a.l$)this.Ea[e.id]||(this.Ea[e.id]=!0,a=b,c=e.marker?nSb(this,
e):oSb(this,e),_.xj(a,7,MRb,c),this.Ba=Math.min(this.Ba,e.TAa),this.Aa=Math.max(this.Aa,KRb(e)));for(var f of this.extras.values())if((e=f.get(hSb))&&e.y$d.length>0)for(var g of e.y$d)e=new VRb,a=g.Qed.getId(fSb),e=_.yi(e,1,a),e=_.Yh(e,2,g.status),g.status===0?(a=_.Yh(e,2,6),_.Yh(a,3,7)):g.incompleteReason&&_.Yh(e,3,g.incompleteReason),a=_.nj(b,WRb,15),_.wh(a,1,VRb,e);g=void 0;f=[];for(let [k,l]of this.extras.entries()){a=k;e=l.get(dSb);if(!e)continue;c=this.oa[a];a=e.Aa;d=e.oa;g!=null||(g=a);e=f;
a=e.push;var h=new TRb;c=_.kk(h,1,c);c=_.kk(c,2,String(d));a.call(e,c.Vd())}g?(g=(new URb).setType(2).Uc(String(g)),f=_.uj(g,4,f).Vd()):f=void 0;f&&_.wh(b,8,URb,f);b.Je(this.Ha.l$[0].name);f=RRb(this.Aa-this.Ba);_.Fb(b,_.cs,11,f);this.La=b.Vd()}isEmpty(){return this.Ha.l$.length===1}};_.hg(_.E$a,class extends _.yo{constructor(a){super();this.config=_.sRb();this.logger=null;this.oa=a.service.yBe.oa}static Ta(){return{service:{yBe:_.ARb}}}init(){this.config.V2c.enabled&&new lSb(this.oa,this.config.V2c.wmc)}});
_.x();
});
// Google Inc.
