loaded_h_0(function(_){var window=this;
_.ENf=_.y("n7qy6d",[]);
_.yNf=!!(_.Ji[94]>>15&1);_.zNf=!!(_.Ji[94]>>16&1);_.ANf=!!(_.Ji[94]>>17&1);_.BNf=!!(_.Ji[94]>>19&1);_.CNf=!!(_.Ji[94]>>20&1);_.DNf=!!(_.Ji[94]>>21&1);
_.v("n7qy6d");
var FNf=function(){var a="getSelection"in window&&"queryCommandSupported"in document&&"execCommand"in document&&document.queryCommandSupported("copy");if(a)try{a=document.execCommand("copy",!0)}catch(b){a=!1}return a},HNf=function(a){if(a.oa&&a.url){GNf(a);var b=a.url,c=a.Ja("tQ9n1c").el();_.bn(c,b);b=document.createRange();b.selectNodeContents(c);window.getSelection().removeAllRanges();window.getSelection().addRange(b);document.execCommand("copy",!0)&&(a.Aa.hide(),a.Ba.show())}},GNf=function(a){var b=
a.getRoot().el();_.Wg(b,"nVW9lb");a.getRoot().getData("ved").Ob()&&_.Vv(a.getRoot().el())},JNf=class extends _.ys{constructor(a){super(a.Oa);this.oa=this.url=null;this.Aa=this.Ja("uu7Hed");this.Ca=this.Ja("axr9cd");this.Ba=this.Ja("pAZ6Ed")}updateUrl(a){if(this.url=a){a=this.url;if(INf){var b=this.Cb("zgnjS");b.size()&&(b.el().textContent=a)}else b=this.Cb("RYUcpc"),b.size()?(_.Lc(b.el(),a),_.bn(b.el(),a||"")):(b=this.Cb("zgnjS"),b.size()&&(_.Io(b,"input").el().value=a));_.jn(this.getRoot().el(),
"visibility",a?"":"hidden");this.Ba.hide();this.Aa.toggle(!!this.oa);this.Ca.toggle(!this.oa)}}setup(){if(this.oa===null){this.oa=FNf();if(INf)this.getRoot().el().addEventListener("copy",a=>{a.clipboardData&&this.url&&(a.clipboardData.setData("text/plain",this.url),a.preventDefault())});else{let a=this.Cb("zgnjS");!this.oa&&a.size()&&(_.Io(a,"input").el().style.cursor="text")}this.Aa.toggle(this.oa);this.Ca.toggle(!this.oa)}}Da(){HNf(this)}Ea(){if(INf)GNf(this);else{HNf(this);var a=this.Cb("zgnjS");
a.size()&&(a=_.Io(a,"input").el(),a.select(),a.focus())}}Ha(){HNf(this)}};JNf.prototype.$wa$RNDhHe=function(){return this.Ha};JNf.prototype.$wa$aiBUrb=function(){return this.Ea};JNf.prototype.$wa$ScPJh=function(){return this.Da};JNf.prototype.$wa$S4w6dd=function(){return this.setup};var INf=_.BNf;_.As(_.ENf,JNf);
_.x();
_.KNf=_.y("HPGtmd",[_.yr]);
_.v("HPGtmd");
var LNf,MNf;LNf=function(a,b){return _.jna(new _.df(a),_.DNa(b)).toString()};MNf=function(a,b,c,d,e){var f,g=(f=a.Wm())!=null?f:"",h;f=(h=a.Yt())!=null?h:"";h=a.n3();var k;g=a.Us(f,g,((k=a.Aa)==null?0:k.Aa())?"\n\n":"\n");var l;if((l=a.ym)==null?0:l.Pa()){let n;g+="\n\n"+((n=a.ym)==null?void 0:n.Na())}d=Object.assign({},d,{body:g});h&&(d[e]=h);b=LNf(b,d);a.dqa(c,b,!_.ji(a.getData("mobile"),!1))};
_.NNf=class extends _.ys{static Ta(){return{service:{navigation:_.fw}}}constructor(a){super(a.Oa);this.oa=this.Ba=this.Aa=this.ym=null;this.navigation=a.service.navigation;if(this.Ba=this.Ya("GIN7Bd").first())this.oa=this.Gc(this.Ba.el(),_.To).then(b=>b)}async setup(){var a=(0,_.Wf)(),b=a();a=a(1);try{this.oa&&a(await b(this.oa)).setup()}finally{b()}}Na(a){var b=LNf("https://www.reddit.com/submit",{url:this.Wm()});this.dqa(a,b,!0)}Ea(a){var b={url:this.Wm()},c=this.Yt();c.length&&(b.text=c);b=LNf("https://www.twitter.com/share",
b);this.dqa(a,b,!0)}Ha(a){var b=this.Yt(),c;b=LNf("https://api.whatsapp.com/send",{text:this.Us(b,this.Wm(),((c=this.Aa)==null?0:c.Aa())?"\n\n":" ")});this.dqa(a,b,!0)}Da(a){var b=LNf("https://www.facebook.com/sharer/sharer.php",{u:this.Wm()});this.dqa(a,b,!0)}Ca(a){MNf(this,"mailto:",a,{},"subject")}Ma(a){MNf(this,"https://mail.google.com/mail",a,{view:"cm",fs:"1",tf:"1"},"su")}La(){return this.Ja("RgELLe").el()}dqa(a,b,c){c?_.Bo(b,{target:"_blank"}):this.navigation.oa(b);b=this.getRoot().el();_.Wg(b,
"nVW9lb");b=this.getRoot().el();_.Wg(b,"dBhwS");a=a.targetElement;a.getData("ved").Ob()&&_.Vv(a.el())}n3(){return this.ym?this.ym.n3()||this.ym.getTitle()||null:null}Wm(){if(this.ym){let a=this.ym.Da()||this.ym.Ca();if(a)return a}throw Error("om");}Yt(){if(!this.ym)return"";var a;return this.ym.Yt()||(((a=this.Aa)==null?0:a.Ba())?"":this.ym.getTitle())||""}Us(a,b,c=" "){if(!this.ym)return"";if(a==="")return b;if(b==="")return a;var d;return((d=this.Aa)==null?0:d.Aa())?b+c+a:a+c+b}};
_.NNf.prototype.$wa$nR7Ch=function(){return this.La};_.NNf.prototype.$wa$eOZhO=function(){return this.Ma};_.NNf.prototype.$wa$NmUBTc=function(){return this.Ca};_.NNf.prototype.$wa$rT2OA=function(){return this.Da};_.NNf.prototype.$wa$cmaSVb=function(){return this.Ha};_.NNf.prototype.$wa$re2RZb=function(){return this.Ea};_.NNf.prototype.$wa$ED9Thd=function(){return this.Na};_.NNf.prototype.$wa$S4w6dd=function(){return this.setup};_.As(_.KNf,_.NNf);
_.x();
_.ONf=_.y("uLYJpc",[_.KNf,_.tr]);
_.v("uLYJpc");
var RNf=async function(a,b){var c=(0,_.Wf)(),d=c();c=c(1);try{let e;(e=a.Ba)==null||e.removeAttr("data-ved");let f;(f=a.Ya("bVp1N").first())==null||f.removeAttr("data-ved");a.Ja("RgELLe").removeAttr("data-ved");a.Ja("P8lkFb").removeAttr("data-ved");a.Cb("EcD0F").removeAttr("data-ved");a.ym=b;if(a.oa)c(await d(a.oa)).updateUrl(a.Wm());else return Promise.resolve()}finally{d()}},SNf=async function(a,b){var c=(0,_.Wf)(),d=c();c=c(1);try{b.pBa&&(a.ym.h4b(b.pBa),a.oa&&c(await d(a.oa)).updateUrl(a.Wm()))}finally{d()}},
UNf=async function(a,b){var c=(0,_.Wf)(),d=c();c=c(1);try{try{let e=c(await d(b));c(await d(SNf(a,e)))}catch(e){if(c(),!("function"==typeof TNf&&e instanceof TNf))throw e;}}finally{d()}},TNf=class extends Error{};var VNf=async function(a,b,c){var d=(0,_.Wf)(),e=d();d=d(1);try{if(a.ym=b,d(await e(RNf(a.zYa,b))),c){var f=a.zYa;if(c.zed){let g;(g=f.Ba)==null||g.setData("ved",c.zed)}if(c.fId){let g;(g=f.Ya("bVp1N").first())==null||g.setData("ved",c.fId)}c.gId&&f.Ja("RgELLe").setData("ved",c.gId);c.jId&&f.Ja("P8lkFb").setData("ved",c.jId);c.lId&&f.Cb("EcD0F").setData("ved",c.lId)}}finally{e()}},XNf=async function(a){var b=(0,_.Wf)(),c=b();b=b(1);try{if(!a.La){if(WNf)if(a.config&&_.rh(a.config,1)){let h=_.u(a.config,
1)||"";a.Nca.Zb(h).show()}else a.Nca.hide();else if(_.rh(a.config,1)){let h=_.u(a.config,1)||"";a.Nca.Zb(h).show();a.Ha.addClass("UrmYj")}else a.Nca.hide(),a.Ha.removeClass("UrmYj");var d=a.zYa,e=!!_.PNf(a.config);d.Ja("RgELLe").toggle(!e);var f=a.zYa,g=!!_.QNf(a.config);f.Ja("P8lkFb").toggle(!g);b(await c(a.zYa.setup()));a.La=!0}}finally{c()}},ZNf=function(a,b){b.aK.then(()=>{YNf(a,b.event)});return!0},$Nf=function(a,b){var c=a.oa.getBoundingClientRect(),d=c.height;if(b.width>0&&b.height>0){if(window.innerHeight-
b.bottom-15>d)d=b.bottom+15;else{var e=b.top-15-d;d=e>0?e:(window.innerHeight-d)/2}b=b.left;e=window.innerWidth-40;b+c.width>e&&(b=e-c.width)}else d=(window.innerHeight-d)/2,b=(window.innerWidth-c.width)/2;a.oa.style.top=`${d}px`;a.oa.style.left=`${b}px`},YNf=function(a,b){a.Aa&&a.Ca&&(a.Aa.classList.remove(a.Ca),a.Ca="");var c=[WNf?a.oa:a.Da];a.Ba&&(c.push(a.Ba),a.Ba=null);_.Uv(c.filter(d=>_.We(d)).map(d=>new _.jo(d,"hide")));a.Aa&&(_.Wg(a.Aa,"tfcxtb",b),a.Aa=null);WNf&&window.removeEventListener("resize",
a.Ea)},aOf=class extends _.ys{static Ta(){return{controller:{zYa:{jsname:"b0t70b",ctor:_.NNf}},Xc:{Mf:{jsname:"Sx9Kwc",ctor:_.zh}},service:{overlay:_.tv}}}constructor(a){super(a.Oa);this.Ma=this.Ha=this.oa=this.Mf=this.Da=null;this.La=!1;this.Aa=this.ym=this.Ba=null;this.Ca="";this.Ea=()=>{this.close()};this.Oe=a.service.overlay;this.zYa=a.controller.zYa;this.Nca=this.Ja("Sy6N1c");WNf?(this.oa=this.Ja("EvA93").el(),this.addOnDisposeCallback(()=>{window.removeEventListener("resize",this.Ea)})):(this.Ma=
this.Ja("tqp7ud").el(),this.Da=this.Ja("Sx9Kwc").el(),this.Ha=this.Ja("OGvssd"),this.Mf=a.Xc.Mf);this.config=new _.YO}async show(a,b,c,d,e,f){var g=(0,_.Wf)(),h=g();g=g(1);try{let k;d&&(k=f||d.getBoundingClientRect(),e&&(this.Aa=d,this.Ca=e,this.Aa.classList.add(e)));g(await h(VNf(this,a,b)));this.setConfig(c||new _.YO);g(await h(XNf(this)));if(WNf){a=k!=null;let l=_.zv(_.Cv(_.Dv(new _.Ev,a?0:1),a),n=>ZNf(this,n));_.Wo(this,this.oa);g(await h(this.Oe.open(this.oa,l)));a?$Nf(this,k):(this.oa.style.top=
"",this.oa.style.left="");window.addEventListener("resize",this.Ea)}else this.Mf.oa(this.Ma);b&&(this.Ba=b.qxb,g(await h(_.Uv([WNf?this.oa:this.Da,b.qxb].filter(l=>_.We(l)).map(l=>new _.jo(l,"show"))))))}finally{h()}}async Pa(a,b,c,d,e,f,g){var h=(0,_.Wf)(),k=h();h=h(1);try{let l=c.then(n=>{var q;if(a.Ma()!==((q=this.ym)==null?void 0:q.Ma()))throw new TNf;return n});h(await k(this.show(a,b,d,e,f,g)));h(await k(UNf(this.zYa,l)))}finally{k()}}Na(a){YNf(this,a.event)}close(){WNf?this.Oe.close(this.oa):
this.Mf.close()}stopPropagation(){}setConfig(a){this.config=a;this.La=!1;this.zYa.Aa=a}};aOf.prototype.$wa$mLt3mc=function(){return this.stopPropagation};aOf.prototype.$wa$TvD9Pc=function(){return this.close};aOf.prototype.$wa$SlAvWb=function(){return this.Na};var WNf=_.BNf;_.As(_.ONf,aOf);
_.x();
});
// Google Inc.
