loaded_h_0(function(_){var window=this;
_.v("IoGlCf");
_.HEd=new _.Zf(_.t3a);
_.x();
_.kG=_.y("C8HsP",[_.t3a]);
_.v("C8HsP");
var IEd,KEd;_.lG=new Set;IEd=function(a,b){b.Ha()||(a=_.Og(a.getRoot().el(),c=>c instanceof Element&&_.og(c,"ved"),!0))&&(a=_.ng(a,"ved"))&&b.Ca(a)};_.mG=function(a,b){var c;a.getRoot().el().setAttribute("data-vhid",(c=b==null?void 0:b.cW())!=null?c:"");IEd(a,b);a.Ha.resolve(b);a.zRc(b)};_.JEd=function(a,b,c){IEd(a,c);a.Aa.set(b,c);a.Ea=!0};
KEd=function(a,b,c,d){if(b.event){var e;let k;(k=(e=b.event).preventDefault)==null||k.call(e);let l,n;(n=(l=b.event).stopPropagation)==null||n.call(l)}c&&IEd(a,c);var f;d=d?(f=_.ng(d,"ved"))!=null?f:void 0:void 0;f=a.Ca(b);var g,h;e=((g=b.ub)==null?0:g.el())?_.og((h=b.ub)==null?void 0:h.el(),"hsr"):!1;a.trigger("aevozb",{eLe:c,interactionVed:d,Gh:f,Zha:e})};
_.nG=class extends _.Cs{static Ta(){return{service:{wJa:_.HEd}}}constructor(a){super(a.Oa);this.Aa=new Map;this.Ea=!1;this.Ha=_.Df();this.wJa=a.service.wJa;this.trigger("k7WJpc")}Pa(a){a.data.element?_.JEd(this,a.data.element,a.data.wr):_.mG(this,a.data.wr)}async JB(){return await this.Ha.promise}Tc(a){if(this.Ea){let b=a.targetElement.el(),c=this.getRoot().el();for(;b&&b!==c;){if(this.Aa.has(b))return KEd(this,a,this.Aa.get(b),b),!1;b=b.parentElement}c&&this.Aa.has(c)?KEd(this,a,this.Aa.get(c),c):
KEd(this,a)}else KEd(this,a);return!1}Ca(a){return(a=a.ub.el())?Number(_.ng(a,"ictx"))||void 0:void 0}zRc(a){var b;(a=(b=a.Ba())==null?void 0:b.getViewerType())&&_.lG.has(a)&&this.wJa.zRc(a)}async bYb(a){this.trigger("vcOT6c",a)}Sa(){return!1}};_.nG.prototype.$wa$M5Scjd=function(){return this.Sa};_.nG.prototype.$wa$zYAnae=function(){return this.Ca};_.nG.prototype.$wa$h5M12e=function(){return this.Tc};_.nG.prototype.$wa$mKCalb=function(){return this.JB};_.nG.prototype.$wa$kNqZ1c=function(){return this.Pa};
_.Es(_.kG,_.nG);
_.lG.add(10);_.lG.add(15);_.lG.add(16);_.lG.add(18);_.lG.add(19);_.lG.add(25);_.lG.add(36);_.lG.add(21);_.lG.add(22);_.lG.add(23);_.lG.add(24);_.lG.add(26);_.lG.add(27);_.lG.add(28);_.lG.add(29);_.lG.add(31);_.lG.add(40);_.lG.add(32);_.lG.add(33);_.lG.add(35);
_.lG.add(10);
_.x();
_.TFd=_.y("gOTY1",[_.Cza,_.t3a]);
_.wG=class extends _.m{constructor(a){super(a)}};_.wG.prototype.rb="PFrTzf";
_.WEd=function(a,b){return _.zk(a,1,b)};_.XEd=function(a){return _.oj(a,_.Hu,1,_.UEd)};_.YEd=function(a,b){return _.tj(a,1,_.UEd,b)};_.uG=function(a,b){return _.eh(a,3,b)};_.vG=function(a,b){return _.Fb(a,_.qG,4,b)};_.ZEd=_.Sb(_.tG);
_.v("gOTY1");
var UFd=function(a){var b=a.getRoot().el();a=[...b.querySelectorAll('[data-viewer-entrypoint]:not([data-nv="1"])')];return a.length===0?a:a.filter(c=>{for(c=c.parentElement;c!==null&&c!==b;){if(c.hasAttribute("data-viewer-group"))return!1;c=c.parentElement}return!0})},WFd=async function(a,b,c=null,d=null){var e=(0,_.Wf)(),f=e();e=e(1);try{let g=e(await f(Promise.all(b.map(n=>VFd(a,n))))),h=new Set,k=g.filter(n=>h.has(n.cW())?!1:(h.add(n.cW()),!0)),l=_.bFd(_.aFd(new _.$Ed,k),a.streamId);a.llc&&l.setQuery(a.llc);
if(c&&d){let n=b.indexOf(c);n>=0&&_.fj(l,1,_.tG,n,d)}return l}finally{f()}},VFd=function(a,b){if(a.Ca.has(b))return a.Ca.get(b);var c=XFd(a,b);a.Ca.set(b,c);return c},XFd=async function(a,b){var c=(0,_.Wf)(),d=c();c=c(1);try{if(_.CFd)try{return c(await d(a.Nk.resolve(b,_.tG)))}catch(e){c()}return c(await d(a.Gc(b,_.Vo))).JB()}finally{d()}},YFd=class extends _.Cs{static Ta(){return{service:{Nk:_.M_a,wJa:_.HEd},If:{Xga:_.wG}}}constructor(a){super(a.Oa);this.Ca=new Map;this.oa=[];this.Ba=this.Aa=null;
this.Da=Promise.resolve();this.Nk=a.service.Nk;this.wJa=a.service.wJa;var b,c;this.streamId=(c=(b=_.qm(this.getData("id")))!=null?b:_.qm(this.getData("vssid")))!=null?c:"global";this.llc=_.qm(this.getData("q"));this.Xga=a.If.Xga;_.CFd||this.Zo(this.initialize(),_.xo)}async initialize(){var a=(0,_.Wf)(),b=a();a=a(1);try{let c=UFd(this);a(await b(this.Ulb(c)))}finally{b()}}async Gxb(a){var b=(0,_.Wf)(),c=b();b=b(1);try{let e=a.targetElement.el();var d;let f=(d=a.data.eLe)!=null?d:null;d=f?e:null;let g=
void 0;if(_.CFd){let l=UFd(this);g=b(await c(WFd(this,l,d,f)))}else this.Aa===d&&this.Ba===f||b(await c(this.Ulb(this.oa,d,f)));let h=f!=null?f:b(await c(VFd(this,e))),k;b(await c(this.wJa.c7({streamId:this.streamId,jx:h.cW(),SFd:e,Jdd:_.Dwa(a)+_.Bh,TFd:_.Aj(h,5),interactionVed:a.data.interactionVed,Gh:a.data.Gh,replace:!!a.data.Zha,Xga:(k=this.Xga)!=null?k:void 0,stream:g})))}finally{c()}}jJc(a){this.wJa.bYb(a.data)}async Ea(a){var b=(0,_.Wf)(),c=b();b=b(1);try{let d=a.targetElement.el();if(!_.CFd&&
!this.oa.includes(d)){let e=UFd(this);b(await c(this.Ulb(e,this.Aa,this.Ba)))}}finally{c()}}async Ha(){var a=(0,_.Wf)(),b=a();a=a(1);try{if(!_.CFd){let c=UFd(this);a(await b(this.Ulb(c,this.Aa,this.Ba)))}return!0}finally{b()}}async Ulb(a,b=null,c=null){var d=(0,_.Wf)(),e=d();d=d(1);try{let f=this.oa;this.oa=a;this.Aa=b;this.Ba=c;let g=this.Da,h=new _.gr;this.Da=h.promise;d(await e(g));let k=d(await e(WFd(this,a,b,c)));a.length>0&&f.length===0?d(await e(this.wJa.Ulb(this,k))):d(await e(this.wJa.iYe(this,
k)));h.resolve()}finally{e()}}Sb(){_.CFd||this.wJa.jOd(this,this.streamId)}};YFd.prototype.$wa$k4Iseb=function(){return this.Sb};YFd.prototype.$wa$sCDZjb=function(){return this.Ha};YFd.prototype.$wa$beCLof=function(){return this.Ea};YFd.prototype.$wa$C6KsF=function(){return this.jJc};YFd.prototype.$wa$T2P31d=function(){return this.Gxb};_.Es(_.TFd,YFd);
_.x();
_.v("LywGEb");

_.x();
_.hOh=function(a,b){return _.eh(a,9,b)};_.iOh=function(a,b){return _.eh(a,10,b)};_.jOh=function(a,b){return _.eh(a,12,b)};_.kOh=function(a){return _.Aj(a,1)};_.lOh=function(a,b){return _.yi(a,3,b)};_.mOh=class extends _.m{constructor(a){super(a)}};_.mOh.prototype.rb="L63THe";_.nOh=function(a,b){return _.eh(a,2,b)};_.oOh=function(a,b){return _.Fb(a,_.oK,3,b)};_.pOh=function(a,b){return _.Fb(a,_.oK,4,b)};var qOh=[0,_.F,_.D];_.rOh=class extends _.m{constructor(a){super(a)}oOb(){return _.Lj(this,2)}};_.rOh.prototype.rb="FFahJe";var sOh=[0,_.F,_.Il,_.C,_.F];var tOh=class extends _.m{constructor(a){super(a)}};tOh.prototype.rb="IV0Wqf";var uOh=[0,_.F,-1];_.vOh=function(a,b){return _.eh(a,3,b)};_.wOh=function(a,b){return _.eh(a,4,b)};_.xOh=function(a,b){return _.eh(a,13,b)};
_.yOh=class extends _.m{constructor(a){super(a,37)}uJ(){return _.u(this,3)}j9(){return _.Aj(this,3)}aD(){return _.u(this,4)}aoa(){return _.Aj(this,4)}Af(){return _.u(this,5)}Hx(){return _.rh(this,5)}pv(){return _.u(this,11)}sK(){return _.u(this,13)}Vgb(){return _.rh(this,13)}jka(){return _.Aj(this,13)}KOb(){return _.u(this,18)}vdc(){return _.Zi(this,_.rOh,19)}Xm(){return _.u(this,31)}xgb(){return _.p(this,tOh,32)}};_.yOh.prototype.rb="onFC6b";_.BS=_.Gb(2003,_.pK,_.yOh);_.cAe[2003]=[-37,{},_.F,-4,_.D,1,_.F,1,_.D,_.F,_.D,_.F,4,_.F,sOh,1,qOh,1,_.D,1,_.D,2,_.D,_.F,1,_.F,uOh,1,_.F,_.Qo,_.D];
_.v("MI2fVb");
_.UZo=function(a,b){var {GGb:c,L2b:d}=b&&b.startsWith("http:")?{GGb:b.replace(/^http:/,"https:"),L2b:!0}:{GGb:b,L2b:!1},e;return a.Ba().then(f=>{e=f;return new _.Rg((g,h)=>{f.addEventListener("load",()=>void g({fNa:f,GGb:c,L2b:d}));f.addEventListener("error",()=>void h({fNa:f,GGb:c,L2b:d}));f.src=c})}).GC(f=>{if(f instanceof _.pf&&e)e.src="";else throw f;})};
_.VZo=function(a,b){b.setAttribute("jsaction",a.getAttribute("jsaction")||"");b.setAttribute("class",a.getAttribute("class")||"");b.setAttribute("style",a.getAttribute("style")||"");b.setAttribute("alt",a.getAttribute("alt")||"");a.getAttribute("role")&&(b.setAttribute("role",a.getAttribute("role")||""),b.setAttribute("tabindex",a.getAttribute("tabindex")||""),b.setAttribute("aria-label",a.getAttribute("aria-label")||""),b.setAttribute("aria-pressed",a.getAttribute("aria-pressed")||""));return b};
_.WZo=class extends _.yo{static Ta(){return{service:{DA:_.Vu}}}constructor(a){super();this.Ca=null;this.An=a.service.DA;this.Aa()}Aa(){}oa(){}Ba(){return _.Ig(new Image)}};_.hg(_.J3a,_.WZo);
_.x();
_.j4h=function(a){return _.Dj(a,2)};_.k4h=function(a){return _.Yh(a,2,2)};_.l4h=function(a){return _.Yh(a,3,2)};
var u3h=class extends _.m{constructor(a){super(a)}};u3h.prototype.rb="LMXOyf";_.v3h=_.Gb(2009,_.pK,u3h);_.cAe[2009]=[0,_.D];
_.v("cNgdQc");
var jZo,iZo,hZo,gZo;
_.kZo=function(a){if(a){var b=a.getImage(),c,d=b==null?void 0:(c=b.getExtension(_.BS))==null?void 0:c.uJ(),e;d&&((e=_.Xc(d))==null?0:e.match(/\.gstatic\.com$/))&&_.gla(d)==="/licensed-image"&&(b==null||_.Yh(b,1,18));switch(b==null?void 0:_.ek(b,1)){case 16:c=a.Ca;d=new _.hAe;d=_.Zh(d,5,!0);d=_.Yh(d,6,2);c=c.call(a,d);d=c.Ba;e=gZo(hZo(iZo(_.l4h(_.k4h(new _.gAe)))));e=_.Zh(e,5,!0);d.call(c,e);break;case 9:case 19:a.Ba(gZo(hZo(iZo(_.l4h(_.k4h(new _.gAe))))));break;case 18:a.Ba(_.k4h(jZo(iZo(new _.gAe))));break;
case 20:a.Ba(jZo(_.k4h(new _.gAe)));break;case 23:a.Ba(gZo(hZo(iZo(_.l4h(jZo(_.k4h(new _.gAe)))))))}var f,g;c=(g=b==null?void 0:_.B(b,9))!=null?g:!1;g=(b==null?void 0:_.Dj(b,1))===18;(c||g||(b==null?void 0:(f=b.Rd(_.v3h))==null?void 0:_.bi(f,1))===!0||(b==null?0:_.B(b,22)))&&_.l4h(a.Da())}};_.lZo=function(a){a&&(a.oa(_.BS,a.Rd(_.BS)||new _.yOh),a=a.getExtension(_.BS),a.sK()||_.xOh(a,a.KOb()||_.Xc(a.uJ()||"")))};jZo=function(a){return _.Yh(a,1,2)};iZo=function(a){return _.Yh(a,4,2)};
hZo=function(a){return _.Yh(a,7,2)};gZo=function(a){return _.Yh(a,8,2)};
_.x();
_.Eri=function(a){var b=new _.zri,c=_.ng(a,"graftType");b.Aa=c;b=_.Ari(b,_.ng(a,"asyncType"));c=_.ng(a,"asyncActions");b.Ba=c;c=_.ng(a,"asyncRclass");b.oa=c;c=_.ng(a,"asyncContextRequired");b.Ca=c;b=_.Bri(_.Cri(_.Dri(b,_.ng(a,"asyncFc")),_.ng(a,"asyncFcv")),_.ng(a,"asyncOns"));a=_.ng(a,"asyncElrc");b.Ea=a;return b};_.Ari=function(a,b){a.La=b;return a};_.Dri=function(a,b){a.Da=b;return a};_.Cri=function(a,b){a.Ma=b;return a};_.Bri=function(a,b){a.Ha=b;return a};_.Fri=function(a,b){a.y8=b;return a};
_.zri=class{build(){var a=_.Qm("DIV");this.id&&(a.id=this.id);this.y8&&_.mg(a,"ved",this.y8);this.Aa&&_.mg(a,"graftType",this.Aa);this.La&&_.mg(a,"asyncType",this.La);this.Ba&&_.mg(a,"asyncActions",this.Ba);this.oa&&_.mg(a,"asyncRclass",this.oa);this.Ca&&_.mg(a,"asyncContextRequired",this.Ca);this.Da&&_.mg(a,"asyncFc",this.Da);this.Ma&&_.mg(a,"asyncFcv",this.Ma);this.Ha&&_.mg(a,"asyncOns",this.Ha);this.Ea&&_.mg(a,"asyncElrc",this.Ea);_.mg(a,"jiis","up");return a}Sc(a){this.id=a;return this}};
_.X8h=function(a,b){return _.eh(a,5,b)};_.Y8h=function(a,b){return _.eh(a,6,b)};_.Z8h=function(a,b){return _.eh(a,7,b)};_.$8h=class extends _.m{constructor(a){super(a)}getImageUrl(){return _.u(this,9)}Fo(){return _.rh(this,9)}Aa(){return _.Aj(this,9)}uJ(){return _.u(this,11)}j9(){return _.Aj(this,11)}getQuery(){return _.u(this,12)}setQuery(a){return _.eh(this,12,a)}Nh(){return _.rh(this,12)}};_.a9h=[0,[0,_.Ql,_.F,-1,_.Uk,_.bm],-1,2,_.F,-8,_.D,-1];_.b9h=_.Ob(_.a9h);
_.FPh=function(a,...b){var c,d;return`1:${((c=window.google)==null?void 0:(d=c.erd)==null?void 0:d.bv)||""}:${a}:${b.length}:${b.join("|")}${_.rx?":d":""}`};
_.v("ukVXp");
_.fZo=!!(_.Ji[59]&1024);


_.x();
var dRh;_.cRh=function(a){return a};_.eRh=function(a){if((a=dRh.querySelector(`#${a}`))&&a instanceof HTMLTemplateElement)return a};dRh=document;
var iKp,lKp,mKp,nKp,oKp,pKp,qKp,rKp,kKp,sKp;_.jKp=function(a){var b=_.eRh(a);return b?c=>{var d=b.hasAttribute("data-ceid")?new _.Hlg(b.getAttribute("data-ceid"),_.Zma(_.gWc(c))):null,{node:e,pH:f}=_.nQ(iKp);e.appendChild(b.content.cloneNode(!0));return{Rha:e,sza:!0,h_:{dispatch:()=>{f({wg:_.yD(c)});d==null||d.dispatch()}},source:1}}:null};
iKp=function(a){kKp(a);var b="<div"+_.W("")+_.X("")+_.V(lKp(a)+"")+">";var c=_.Zz(a),d=a.Da();d!==""&&(b+=" <style>"+d+"</style>");b+=c+_.Zz(a)+"</div>";a.Ea();return _.z(b)};lKp=function(a){return _.Yz(a,{Jb:233505,track:[4,3]}).attributes};mKp=function(){return""};nKp=function(){return""};oKp=function(){return!0};pKp=function(){return!1};qKp=function(a){kKp(a);return _.Zz(a)};rKp=function(a){kKp(a);var b="<div"+_.W("")+_.X("")+_.V(lKp(a)+"")+">";var c=_.Zz(a);b+=c+_.Zz(a)+"</div>";return _.z(b)};
kKp=function(a){a.oa(sKp)||a.Aa(sKp,{},qKp,rKp,oKp,pKp,"",lKp,"",mKp,"",nKp)};sKp="t-EAc4Jloiu8E";
_.pG[477233885]=[0,_.F,-1];
_.p5h=_.y("nKrFPc",[_.ss]);
_.Y_h=function(a){var b=_.X_h();return _.Zh(b,8,a)};_.Z_h=function(a,b){return _.Zh(a,9,b)};_.X_h=function(){var a=new _.$_h;return _.Zh(a,10,!0)};_.$_h=class extends _.m{constructor(a){super(a)}rk(){return _.u(this,2)}Mv(){return _.rh(this,2)}};_.$_h.prototype.rb="ZEIdFc";
_.q5h=_.xu({Lg:!1,name:"fC4dIb",Jg:_.p5h,params:{ctor:class extends _.m{constructor(a){super(a)}}},Sg:[],data:{Xga:function(){},Kdg:function(){},kc:function(){},jfa:function(){},ujg:function(){}},Rg:()=>({variant:null,Dg:[],Eg:{}}),Qg:{},children:{}});
var Mzg=class extends _.m{constructor(a){super(a)}getQuery(){return _.u(this,1)}setQuery(a){return _.eh(this,1,a)}Aa(){return _.cf(this,1)}Nh(){return _.rh(this,1)}};Mzg.prototype.rb="TrFC3b";var Nzg={RN(){return["q"]},rl(a,b){_.Hv(new _.Qv(a.searchParams,b),"q",b.setQuery,b.Aa)},Ml(a,b){_.Lv(new _.Qv(b.searchParams,a),a.Nh,a.getQuery,"q")}};var Ozg;Ozg=null;_.AQ=class extends _.Ww{constructor(a,b){super(a);new _.Xw(this);this.vp=_.Uw(b,this,new _.Tw(Nzg))}static Bn(){return Mzg}static Gn(a){return Ozg?Ozg:Ozg=_.Sw().then(b=>{b=new _.AQ(Mzg,b);b.initialize(a);return b})}};_.op.TrFC3b=_.np;
_.rK=class extends _.m{constructor(a){super(a,2)}xD(){return _.ph(this,_.pK,1,_.qh())}};_.rK.prototype.rb="U9CFPc";_.oAe=[-2,{},_.G,_.fAe];
_.pAe=function(a,b){return _.eh(a,1,b)};_.qAe=class extends _.m{constructor(a){super(a)}getId(){return _.u(this,1)}Sc(a){return _.eh(this,1,a)}Eh(){return _.rh(this,1)}Jf(){return _.Aj(this,1)}getTitle(){return _.Uj(this,4,_.iAe)}setTitle(a){return _.pk(this,4,_.iAe,a)}wd(){return _.Kk(this,4,_.iAe)}Pl(){return _.u(this,18)}Wy(){return _.rh(this,18)}getUrl(){return _.u(this,5)}jd(){return _.rh(this,5)}getContentType(){return _.Dj(this,7)}Zld(){return _.Ve(this,19,-1)}};_.qAe.prototype.rb="IRVcEb";
_.rAe=function(a,b){return _.Fb(a,_.pK,2,b)};_.sAe=function(a){return _.p(a,_.qAe,13)};_.tAe=function(a){return _.p(a,_.gAe,15)};_.uAe=_.Sb(_.pK);_.vAe=_.Sb(_.qK);new _.vi(_.pK);_.op.XZxcdf=function(a){return _.pp(_.qp(_.Aj(a,2)))};new _.vi(_.rK);_.op.U9CFPc=_.np;_.hr(_.rK,_.pK,function(a){return a.xD()});_.sK=_.Gb(444383007,_.oG,_.qK);_.pG[444383007]=_.nAe;var wAe=new _.vi(_.qK);wAe.Va=new _.vi(_.qAe);wAe.Bb=_.sK;_.op.j0Opre=function(a){return _.pp(_.qp(a.Jf()))};_.hr(_.qK,_.pK,function(a){a=a.getImage();return a!=null?[a]:[]});_.hr(_.qK,_.qAe,function(a){a=_.sAe(a);return a!=null?[a]:[]});_.op.IRVcEb=function(a){return _.pp(_.qp(a.Jf()))};
_.v("L8BGsc");
var uKp=function(a,b){var {node:c,pH:d}=_.nQ(tKp);b({dispatch:()=>void d({wg:_.yD(a)})});return c},vKp=function(a){a=a==null?void 0:a.replace("e-","");return document.body.querySelector(`[jsname="VVvY3e"][data-tbnid="${a}"]`)},yKp=async function(a,b,c,d){return b?await wKp(a,b,c,d):xKp()},wKp=async function(a,b,c,d){var e=(0,_.Wf)(),f=e();e=e(1);try{let g=e(await f(_.eg(a,{service:{component:_.ps,Ce:_.Yu}}))),h=g.service.component,k=g.service.Ce,l=_.u(b,29)?41:1,n=_.rAe((new _.qK).setType(l),b).Sc(b.getUniqueId());
_.kZo(n);_.lZo(b);let q=_.cJd(new _.qG,(new _.oG).oa(_.sK,n)),r,t=(r=c==null?void 0:c.index)!=null?r:0,A,E=(A=c==null?void 0:c.count)!=null?A:0,H=e(await f(h.fetch(_.q5h,a,null,{kc:q,jfa:_.Z_h(_.Y_h(t>0),t<E-1),Xga:d})));return N=>{var P=_.nQ(_.TQh),{output:S,lTa:Z}=k.amb(()=>H.render(),{Ze:_.Wh(P.node,3)});P.node.appendChild(S);return{Rha:P.node,sza:!0,h_:{dispatch:()=>{P.pH({wg:_.yD(N)});k.Mwa(Z)}},source:2}}}finally{f()}},xKp=async function(){return a=>{var b=_.nQ(zKp);return{Rha:b.node,sza:!1,
h_:{dispatch:()=>{b.pH({wg:_.yD(a)})}},source:3}}},AKp=_.Ub(_.pK),BKp=_.Kb(_.$8h,_.a9h),CKp=function(){return""},DKp=function(){return"height:100%;"},EKp=function(a){return _.Yz(a,{Jb:273509,track:[3]}).attributes},FKp=function(){return!0},GKp=function(){return!1},IKp=function(a){HKp(a);return _.Zz(a)},JKp=function(a){HKp(a);var b="<div"+_.W("")+_.X(DKp(a)+"")+_.V(EKp(a)+"")+">";var c=_.Zz(a);b+=c+_.Zz(a)+"</div>";return _.z(b)},HKp=function(a){a.oa("t-OvacITrwp00")||a.Aa("t-OvacITrwp00",{},IKp,JKp,
FKp,GKp,"",EKp,"",CKp,"",DKp)},tKp=function(a){HKp(a);var b="<div"+_.W("")+_.X(DKp(a)+"")+_.V(EKp(a)+"")+">";var c=_.Zz(a),d=a.Da();d!==""&&(b+=" <style>"+d+"</style>");b+=c+_.Zz(a)+"</div>";a.Ea();return _.z(b)},KKp=function(a){var b,c;return((b=a.xoa)==null?void 0:b.querySelector("[jsname='kn3ccd']"))||((c=a.xoa)==null?void 0:c.querySelector("[jsname='figiqf']"))||a.xoa},LKp=class{constructor(a,b,c,d,e,f){this.pluginData=a;this.oe=b;this.query=c;this.OYa=d;this.source=e;this.Aa=f;this.jn=null;this.isActive=
this.oa=!1}getType(){return 4}getViewerType(){return 7}async fetch(){var a=(0,_.Wf)(),b=a();a=a(1);try{let c,d="",e,f=_.u(this.pluginData,6),g=_.u(this.pluginData,7),h,k=(h=_.u(this.pluginData,8))!=null?h:"";if(f&&g){let {ved:l,UF:n}=_.zD(233506);this.En={element:_.Ari(_.Fri(new _.zri,l),"imgv").Sc(`imgv-${f}-${g}`).build(),ved:l,UF:n};f&&g&&(e=new Map(this.Aa),e.set("tbs",""),e.set("vsrid",null),e.set("tbnid",f),e.set("imgdii",f),e.set("docid",g),e.set("q",this.query),_.B(this.pluginData,15)&&e.set("ssbl",
"1"),this.oa||e.set("fvr","1"),k&&e.set("esprk",k),d=_.FPh("async",`${f}-${g}-${this.oa?"1":"0"}-${k}`))}this.En&&(c=_.U_b(this.En.element,{urlParams:e,Nu:_.hFd?void 0:new _.jw(d)}));this.UDa=a(await b(c))}finally{b()}}VB({Gl:a,Uz:b}){var c=0;this.jn=uKp(a,b);if(this.OYa){let {sza:d,Rha:e,h_:f}=this.OYa(this.jn);b(f);this.xoa=e;this.oa=d;this.xoa.style.height="100%";this.jn.appendChild(this.xoa);c=d?2:1}a.appendChild(this.jn);c===0&&(c=1);return{status:c,source:this.oa?2:1}}async render({Uz:a}){var b=
(0,_.Wf)(),c=b();b=b(1);try{this.En&&(this.En.element.style.display="none",this.jn.appendChild(this.En.element));let d;b(await c((d=this.UDa)==null?void 0:d.render()));if(this.En){let e=_.Xp(this.oe.oa(),this.En.UF),f,g=(f=this.xoa)==null?void 0:f.querySelector("[jsname='xYQ4wd']");g&&(g.replaceChildren(this.En.element),_.$p(e,new _.Vh(_.yD(g),3)));a({dispatch:()=>void e.log(!0)});this.En.element.style.display="";_.pFd&&this.En.element.animate([{opacity:0},{opacity:1}],{duration:250,easing:"cubic-bezier(.75,1,.75,1)"})}this.isActive&&
this.setActive(this.isActive);_.Yg(this.jn,"sm6kQ")}finally{c()}}eId(a){this.jn&&_.Yg(this.jn,a?"OPpNPb":"wMvXeb")}setActive(a){this.isActive=a;if(this.jn){let b=this.jn,c=0;switch(this.source){case 1:c=1;break;case 2:c=2;break;case 5:c=5;break;case 6:c=6;break;case 8:c=8;break;case 9:c=9;break;case 10:c=10}(0,_.Ef)(()=>{_.Yg(b,"qa5owb",this.isActive,c)})}}d4a(){var a="";try{let b,c;a+=((b=this.jn)==null?void 0:(c=b.querySelector("'.Uc5v9'"))==null?void 0:c.textContent)||""}catch(b){}return new Map([["prompt_text",
a]])}i4a(){var a;return(a=this.xoa)==null?void 0:a.querySelector("[jsname='Cdl0yb']")}T5(){var a,b,c;return(c=(a=this.xoa)==null?void 0:a.querySelector("[jsname='tqp7ud']"))!=null?c:(b=this.xoa)==null?void 0:b.querySelector(".VB2c0b")}Hfb(){var a=this.T5();return a?_.We(a):void 0}I4a(){if(_.pFd)return{ihb:KKp(this)}}Gfb(a){if(_.fZo&&!a&&(a=vKp(_.u(this.pluginData,5))))return{MGa:a,jma:!1,OGa:_.hTb};if(_.pFd)return{ihb:KKp(this)}}bXb(){return _.fZo?vKp(_.u(this.pluginData,5))!=null:!1}jCb(a){_.fZo&&
vKp(_.u(this.pluginData,5))!=null&&a!=null&&(a.style.opacity="")}serialize(){return(0,_.b9h)(this.pluginData)}},MKp=function(){return""},NKp=function(){return""},OKp=function(){return""},PKp=function(){return!0},QKp=function(){return!1},TKp=function(a){RKp(a);return SKp(a)},UKp=function(a){RKp(a);a=SKp(a);return _.z(a)},SKp=function(a){var b="<div"+_.W("")+_.X("")+_.V(' jsname="'+_.R("xYQ4wd")+'"')+">";a="<div"+_.W("ZCPy9b ")+_.X("")+_.V(_.kQh(a)+"")+">"+_.lQh(a)+"</div>";return b=b+a+("<div"+_.W("qtKpsd ")+
_.X("")+_.V("")+"></div><div"+_.W("HPzwBf ")+_.X("")+_.V("")+"></div></div>")},RKp=function(a){a.oa(VKp)||(a.Aa(VKp,{},TKp,UKp,PKp,QKp,"",MKp,"",NKp,"",OKp),_.jQh(a))},VKp="t-yGLc6CRbXSY";var zKp=function(a){WKp(a);var b="<div"+_.W("")+_.X("")+_.V("")+">";var c=XKp(a),d=a.Da();d!==""&&(b+=" <style>"+d+"</style>");b+=c+"</div>";a.Ea();return _.z(b)},YKp=function(){return""},ZKp=function(){return""},$Kp=function(){return""},aLp=function(){return!0},bLp=function(){return!1},cLp=function(a){WKp(a);return XKp(a)},dLp=function(a){WKp(a);var b="<div"+_.W("")+_.X("")+_.V("")+">";a=XKp(a);return _.z(b+(a+"</div>"))},XKp=function(a){var b=_.BA(_.pi().Xa),c=_.T("t-yGLc6CRbXSY",{});a.Ba(".qtKpsd{background-color:"+
(_.U(b,"",d=>d.So())+";border-radius:16px;height:16px;left:16px;position:absolute;top:18px;width:90px}"));a.Ba(".HPzwBf{background-color:"+_.U(b,"",d=>d.So())+";height:30vh;width:100%}");return"<div"+_.W(_.IQh(a,c,!0)+"Z7HyUd ")+_.X("")+_.V(_.HQh(a,c,!0)+"")+">"+_.NQh(a,c)+"</div>"},WKp=function(a){a.oa(eLp)||(a.Aa(eLp,{},cLp,dLp,aLp,bLp,"",YKp,"",ZKp,"",$Kp),_.MQh(a),RKp(a))},eLp="t-xZRmxm-kWc4";var fLp,hLp,iLp;fLp=!1;_.gLp=function(a,b){try{let c,d=b==null?void 0:(c=b.Wg())==null?void 0:c.getUrl();d&&_.UZo(a.Aa,d)}catch(c){}};hLp=async function(a,b){var c=(0,_.Wf)(),d=c();c=c(1);try{if(b){if(b.hasAttribute("data-im")){let e;return AKp((e=b.getAttribute("data-im"))!=null?e:"")}if(b.hasAttribute("jsdata"))try{return c(await d(a.oa.resolve(b,_.pK)))}catch(e){c()}}}finally{d()}};
iLp=async function(a,b,c,d){var e=(0,_.Wf)(),f=e();e=e(1);try{let g=b==null?void 0:b.dataset.previewId,h=null;g&&(h=_.jKp(g));if(!h){let k;if((b==null?0:b.hasAttribute("jsdata"))&&_.zVa(b,_.wG))try{k=e(await f(new Promise((l,n)=>{a.oa.resolve(b,_.wG).then(l,n)})))}catch(l){e()}h=e(await f(yKp(a,c,d,k)))}return h}finally{f()}};
_.jLp=class extends _.yo{static Ta(){return{service:{component:_.ps,fNa:_.WZo,Nk:_.M_a,Ce:_.Yu,Kc:_.Wu},Ge:{Fl:_.AQ}}}prefetch(){fLp||(fLp=!0,this.dg.Lpa(_.q5h))}constructor(a){super();this.dg=a.service.component;this.Qd=a.service.Ce;this.Ub=a.service.Kc;this.Fl=a.Ge.Fl;this.oa=a.service.Nk;this.Aa=a.service.fNa}async A2a(a,b,c,d,e){c=(0,_.Wf)();b=c();c=c(1);try{e={entrypoint:a,Nzd:e};let f=(a==null?void 0:a.getAttribute("eqld"))||"",g=new Map;f&&g.set("eqld",f);e.urlParams=g;e.pB=c(await b(hLp(this,
a)));return this.getInstance(e)}finally{b()}}async getInstance(a){var b=(0,_.Wf)(),c=b();b=b(1);try{let f=a.pB,g=a.entrypoint,h=a.urlParams,k=a.Nzd,l=this.Fl.get().getQuery(),n=new _.$8h;if(f){let t=f==null?void 0:f.getUniqueId(),A,E=f==null?void 0:(A=f.Rd(_.BS))==null?void 0:_.u(A,2);var d;if(d=!!t&&!!E&&(f==null?void 0:_.Dj(f,1))!==9){let N;d=(f==null?void 0:(N=f.Rd(_.v3h))==null?void 0:_.B(N,1))!==!0}if(d){let N;_.Z8h(_.Y8h(n,f.getUniqueId()),(N=f.Rd(_.BS))==null?void 0:_.u(N,2))}if(_.u(f,29)){a=
n;var e=_.u(f,29);_.eh(a,8,e)}_.B(f,22)&&_.Zh(n,15,!0);let H;((H=_.p(f,_.mOh,31))==null?0:_.B(H,1))&&_.Zh(n,14,!0);_.gLp(this,f)}g&&_.X8h(n,g.id);let q=b(await c(iLp(this,g,f,k))),r;return new LKp(n,this.Ub,l,q,(r=k==null?void 0:k.source)!=null?r:0,h!=null?h:new Map)}finally{c()}}async kA(a,b,c){var d=(0,_.Wf)();b=d();d=d(1);try{let e=BKp(a),f=this.Fl.get().getQuery(),g=_.u(e,5),h=new Map,k=g?_.RJa(g)||void 0:void 0,l=d(await b(hLp(this,k))),n=(k==null?void 0:k.getAttribute("eqld"))||"";n&&h.set("eqld",
n);let q=d(await b(iLp(this,k,l,c))),r;return new LKp(e,this.Ub,f,q,(r=c==null?void 0:c.source)!=null?r:4,h)}finally{b()}}};_.hg(_.K3a,_.jLp);
_.x();
_.MRh=_.y("BJ46o",[]);
_.v("wVv2xf");
var NTh,OTh,QTh,TTh,UTh,VTh,WTh,XTh,YTh,ZTh,$Th,aUh,cUh,dUh,bUh,eUh,fUh,gUh,hUh,iUh,jUh,kUh,lUh,mUh,nUh,oUh,pUh,qUh,rUh,sUh,tUh,uUh,vUh,wUh,xUh,yUh,zUh,AUh,BUh,CUh,DUh,EUh,FUh,IUh,HUh,LUh,PUh,QUh,OUh,RUh,SUh,TUh,MUh,NUh,GUh,KUh,JUh,VUh;NTh=function(a,b){return a.index-b.index};OTh=function(a){return this-a.index};QTh=async function(a,b){return await _.gg(PTh[a],b)};_.RTh=function(){var a=new _.wS;return _.Zh(a,1,!0)};_.STh=function(a){var b=_.RTh();return _.Yh(b,2,a)};TTh=class extends _.m{constructor(a){super(a)}};
UTh=_.Gb(257,_.Rp,TTh);VTh=class{constructor(a){this.Uz=a;this.oa=[];this.Aa=!1}register(a){this.Aa?this.Uz(a):this.oa.push(a)}dispatch(){this.Aa=!0;for(let a of this.oa)this.Uz(a);this.oa=[]}};WTh=function(){return""};XTh=function(){return""};YTh=function(){return""};ZTh=function(){return!0};$Th=function(){return!1};
aUh=function(a){var b=_.BA(_.pi().Xa),c=_.BA(_.pi().Id),d=_.BA(_.pi().Nc),e=_.BA(_.pi().Ib),f=_.U(d,"",h=>_.Vy(h)),g=_.U(d,"",h=>_.tx(h));a.Ba(".A3u8Sd{align-items:flex-start;display:flex;flex-direction:column;padding:"+f+" "+g+"}");a.Ba(".Xy3gU{color:"+_.U(b,"",h=>_.Fy(h))+";font-family:"+_.U(c,"",h=>h.R5())+";font-size:"+_.U(e,"",h=>_.fw(h))+";font-weight:"+_.U(e,"",h=>_.u(h,52))+";margin-bottom:"+_.U(d,"",h=>_.Sy(h))+"}");a.Ba(".Ztrxxd{color:"+_.U(b,"",h=>_.cp(h))+";font-family:"+_.U(c,"",h=>h.R5())+
";font-size:"+_.U(e,"",h=>_.Yy(h))+";line-height:"+_.U(e,"",h=>_.u(h,44))+"}");b="";a="<div"+_.W("ZCPy9b ")+_.X("")+_.V(_.kQh(a)+"")+">"+_.lQh(a)+"</div>";return b=b+a+("<div"+_.W("Xy3gU ")+_.X("")+_.V("")+">Something went wrong</div><div"+_.W("Ztrxxd ")+_.X("")+_.V("")+">Can't load your result right now. Please try again later.</div>")};cUh=function(a){bUh(a);return aUh(a)};dUh=function(a){bUh(a);var b="<div"+_.W("A3u8Sd ")+_.X("")+_.V("")+">";a=aUh(a);return _.z(b+(a+"</div>"))};
bUh=function(a){a.oa("t-Un4zSljVMDY")||(a.Aa("t-Un4zSljVMDY",{},cUh,dUh,ZTh,$Th,"",YTh,"A3u8Sd ",WTh,"",XTh),_.jQh(a))};eUh=function(a){bUh(a);var b="<div"+_.W("A3u8Sd ")+_.X("")+_.V("")+">";var c=aUh(a),d=a.Da();d!==""&&(b+=" <style>"+d+"</style>");b+=c+"</div>";a.Ea();return _.z(b)};fUh={prev:3589,next:3590};gUh=function(a){var b=a.pka&&a.Ca;_.ke(a.hJ,"hidden",!b);_.RFd||_.QFd||(a.hJ.style.display=b?"":"none");a.hJ.inert=!b};hUh=function(a){var b;return(b=a.oa)!=null?b:null};
iUh=function(a){if(a.pka&&a.Aa&&a.hJ){var b=_.jkc(a.hJ);if(b.length<=0)a.hJ.tabIndex=-1,a.hJ.focus({preventScroll:!0});else{_.zx?(a.cG||(a.cG=new _.wkc(a.hJ),_.ukc(a.cG)),a=_.tkc(a.cG,0)):a=b[0];var c;(c=a)==null||c.focus({preventScroll:!0})}}};jUh=function(a){var b=a.pka&&a.Aa;gUh(a);var c,d;(c=a.oa)==null||(d=c.setActive)==null||d.call(c,b);iUh(a);if(b){let e;(e=a.entrypoint)==null||e.scrollIntoView({block:"nearest"})}};kUh=function(a,b){a.pka!==b&&(a.pka=b,jUh(a))};
lUh=function(a,b){a.Aa!==b&&(a.Aa=b,jUh(a))};mUh=function(a,b){if(a.Ca!==b){a.Ca=b;var c,d;(c=a.oa)==null||(d=c.eId)==null||d.call(c,b);gUh(a);b===!1&&a.mE(!1)}};nUh=function(a,b){if(a.QCa.UF){var c=a.Ub.oa();a.Da||(_.$p(_.Xp(c,a.QCa.UF),new _.Vh(b,3)),a.Da=!0);c.log(!0)}a.h_.dispatch()};
oUh=class{constructor(a,b,c,d,e,f=!1,g=!1,h=!1,k,l){this.Ub=a;this.yT=b;this.index=c;this.Sa=d;this.iS=e;this.pka=f;this.Aa=g;this.Ca=h;this.h_=k;this.Ea=new AbortController;this.pTa=3;this.Ag=0;this.Na=7;this.La=[];this.Ha=0;this.Da=!1;this.Pa={[-1]:null,[1]:null};this.Zsb=null;this.cG=void 0;this.Ma=!1;var n;this.entrypoint=(n=e.cwb)==null?void 0:n.call(e,c);l?(this.QCa={ved:l.dataset.ved,UF:void 0},this.hJ=l):(this.QCa=_.zD(237020,h),{node:a}=_.nQ(q=>{var r=this.pka&&this.Ca,t=this.QCa.ved;_.hTh(q);
var A="";_.BA(_.pi().Nc);A+="<div"+_.W(_.dTh(q,r,t)+"Fp3I9 ")+_.X(_.eTh(q,r,t)+"")+_.V(_.cTh(q,r,t)+"")+">";r=_.iTh();t=q.Da();t!==""&&(A+=" <style>"+t+"</style>");A+=r+"</div>";q.Ea();return _.z(A)}),this.hJ=a);this.hJ.dataset.sci=`${this.index}`;_.cNh(this.hJ);this.Oi=_.Jm("hwRvZe",this.hJ);this.Ua=this.entrypoint?_.yD(this.entrypoint):"";gUh(this)}Ii(a,b){this.pTa=Math.min(a,this.Na);return _.ySh({client:this,Jx:b,vNb:this})}nxd(){return this.Sa}YLc(a,b){this.oa=b;var c,d;(d=(c=this.oa).setActive)==
null||d.call(c,this.pka&&this.Aa)}isActive(){return this.pka&&this.Aa}mE(a){_.$p(this.Ub.oa(),new _.Vh(this.QCa.ved,a?1:2)).log()}async Ba(a){var b=this.Ua;if(b){var c=this.Pa[a];if(c!=null)a=c;else{var d,e,f;let n;c=((f=this.oa)==null?void 0:(n=f.Zle)==null?void 0:n.call(f))||fUh;f=_.zD(a===1?c.next:c.prev,!0,(new _.yp).oa(_.TRh,_.QRh(new _.RRh,((d=this.oa)==null?void 0:(e=d.getViewerType)==null?void 0:e.call(d))||0)));_.$p(_.Xp(this.Ub.oa(),f.UF),new _.Vh(b,3)).log();a=this.Pa[a]=f.ved}var g,h,
k;d=(k=(g=this.oa)==null?void 0:(h=g.Rld)==null?void 0:h.call(g))!=null?k:new _.Vp;g=this.Ub.oa();h=new _.Rp;k=h.oa;e=new TTh;e=_.Yh(e,2,3);g=_.Yp(_.dq(g,_.Tu(d,k.call(h,UTh,e))),new _.Th(a,21));var l;((l=this.QCa)==null?0:l.UF)&&!this.Da&&(_.$p(_.Xp(g,this.QCa.UF),new _.Vh(b,3)),this.Da=!0);g.log(!0);this.h_.dispatch();this.mE(!0)}}Hfb(){var a,b,c;return(c=(a=this.oa)==null?void 0:(b=a.Hfb)==null?void 0:b.call(a))!=null?c:this.Zsb?this.Zsb:this.Zsb=_.uSh(this.Ub,3593,this.QCa.ved)}T5(){var a,b;return(a=
this.oa)==null?void 0:(b=a.T5)==null?void 0:b.call(a)}i4a(){var a,b;return(a=this.oa)==null?void 0:(b=a.i4a)==null?void 0:b.call(a)}I4a(a){var b,c;return(b=this.oa)==null?void 0:(c=b.I4a)==null?void 0:c.call(b,a)}Gfb(a){var b,c;return(b=this.oa)==null?void 0:(c=b.Gfb)==null?void 0:c.call(b,a)}bXb(a){var b,c;return((b=this.oa)==null?void 0:(c=b.bXb)==null?void 0:c.call(b,a))||!1}Cjc(a){var b,c;return((b=this.oa)==null?void 0:(c=b.Cjc)==null?void 0:c.call(b,a))||!1}jCb(a){var b,c;(b=this.oa)==null||
(c=b.jCb)==null||c.call(b,a)}Jcd(){return!1}async Wjd(){var a,b;return this.M8=(b=(a=this.oa).fetch)==null?void 0:b.call(a,{signal:this.Ea.signal})}VB(){this.oa.VB!=null&&(this.Ha=this.oa.VB({Gl:this.Oi,signal:this.Ea.signal,Uz:a=>void this.h_.register(a)}).status);iUh(this);return this.Ha}async render(){var a=(0,_.Wf)(),b=a();a=a(1);try{this.oa.render!=null&&a(await b(this.oa.render({Gl:this.Oi,signal:this.Ea.signal,Uz:c=>void this.h_.register(c)}))),iUh(this),_.Yg(this.hJ,"foUORe",{index:this.index,
count:this.iS.rda()})}finally{b()}}tPa(){this.Oi.textContent="";var {node:a,pH:b}=_.nQ(eUh);this.h_.register({dispatch:()=>void b({wg:_.yD(this.Oi)})});this.Oi.appendChild(a)}HYb(){this.yT()}Qgd(){_.lFd&&this.h_.dispatch()}Xed(){return this.hJ}Zed(){return this.hJ}hUc(){return Promise.resolve()}reposition(a,b){a===0?(this.hJ.classList.remove("jQBzlf"),_.Tx(this.hJ,0,0)):(this.hJ.classList.add("jQBzlf"),_.Tx(this.hJ,a*b,0))}OOa(){if(!this.Ma){this.Ma=!0;try{let a,b;(a=this.oa)==null||(b=a.OOa)==null||
b.call(a)}catch(a){}}}dispose(){for(this.Na=this.pTa=0;this.La.length>0;)_.Tg(this.La.pop());this.Ea.abort()}};pUh=function(a){var b;return(b=a.array.at(-1))!=null?b:null};qUh=function(a,b,c){for(;a.map.size>=_.jMh;){var d=a,e=b;let f=void 0,g=(f=d.array[0])!=null?f:null;d=pUh(d);e=g!=null&&d!=null?Math.abs(e-g.index)>Math.abs(e-d.index)?g:d:g!=null?g:d;a.remove(e.index);c(e)}};
rUh=class{constructor(){this.map=new Map;this.array=[]}yk(){return this.map.size}get(a){var b;return(b=this.map.get(a))!=null?b:null}getAll(){return this.array}add(a){this.yk();this.get(a.index);this.map.set(a.index,a);_.rba(this.array,a,NTh)}remove(a){this.map.delete(a);a=_.oba(this.array,OTh,a);a>=0&&this.array.splice(a,1)}};
sUh=function(a,b,c,d){c.appendChild(a.Os);c.style.overscrollBehavior="contain";a.pH&&d({dispatch:()=>{var f=_.yD(c);a.pH({wg:f})}});var e=a.Uo.oa(a.Os,f=>{a.Aa=f.at(-1).contentRect.width;a.Aa>0&&(a.Ca.resolve(),_.Wg(a.Os,"CdDuO"))});b.addEventListener("abort",()=>{a.Os.remove();a.Uo.Aa(e);a.Ca=Promise.withResolvers()},{once:!0})};tUh=function(a,b,c){a.Os.addEventListener("focus",c,{signal:b})};
uUh=function(a,b,c){a.Os.addEventListener("touchstart",c,{signal:b});a.Os.addEventListener("touchmove",c,{signal:b,passive:!1})};vUh=function(a,b,c){a.Os.addEventListener("touchend",c,{signal:b});a.Os.addEventListener("touchcancel",c,{signal:b})};wUh=function(a,b,c){a.Os.addEventListener("keydown",d=>{a:switch(d.key){case "ArrowRight":var e=1;break a;case "ArrowLeft":e=-1;break a;default:e=0}e!==0&&(d.preventDefault(),c(e))},{signal:b})};
xUh=function(a,b){_.Sg(a.Os,"F4Y6ee",()=>{b(1)});_.Sg(a.Os,"uZTYG",()=>{b(-1)})};yUh=function(a,b,c){a.Os.addEventListener("transitionend",c,{signal:b})};zUh=function(a){a=_.ln(a.Os,"transform");return(new DOMMatrixReadOnly(a)).e};AUh=function(a,b,c){c&&zUh(a);var d=c?`transform ${_.kMh} ease-in-out`:"";a.Os.style.transition=d;a.Os.style.transform=`translateX(${b}px)`;a.oa&&(a.oa.style.transition=d,a.oa.style.transform=`translateX(${-b}px)`);return c&&a.Os.getAnimations().length>0};
BUh=function(a){return a.Aa+a.Da};CUh=function(a,b,c,d=!1){a.oa&&(a.Ba.position=b,a.Ba.count=c,a.Ba.animate=d,_.Yg(a.oa,"KF9ZEf",a.Ba))};DUh=function(a,b){a.oa&&_.Wg(a.oa,"X5vnkc",{TQ:b.index,Tcd:b.Oi})};
EUh=class{constructor(a,b,c){this.Uo=a;this.Ca=Promise.withResolvers();this.Aa=0;this.oa=null;this.Ba={position:0,count:0,animate:!1};if(c)this.Os=c;else{let {node:e,pH:f}=_.nQ(g=>{var h=b!=null?b:null;_.HTh(g);var k="";_.BA(_.pi().Nc);h==null&&new _.wS;k+="<div"+_.W(_.DTh(g,h)+"HV5Yde ")+_.X(_.ETh(g,h)+"")+_.V(_.CTh(g,h)+"")+">";h=_.ITh(g,h);var l=g.Da();l!==""&&(k+=" <style>"+l+"</style>");k+=h+_.Zz(g)+"</div>";g.Ea();return _.z(k)});this.pH=f;this.Os=e}var d;this.Da=Number((d=this.Os.dataset.gap)==
null?void 0:d.replace("px",""))||0;if(b==null?0:_.B(b,1))this.oa=_.wMb("MPaS6",this.Os),_.Sg(this.Os,"frjz1d",e=>{if(this.oa){var f=e.data;e=_.gn(e.targetElement.hb(),"Fp3I9");_.Wg(this.oa,"kr34C",{TQ:Number(e.dataset.sci),scrollTop:f})}})}isInstalled(){return this.Os.isConnected}yT(a){_.Wg(this.Os,"KpPeYd",a)}did(){this.Os.style.pointerEvents=""}};FUh=function(a){return a.Gca.get(a.Rl.OC)};
IUh=function(a,b,c){b=GUh(a,a.Rl.OC+b);a.Rl.ZEb=b;AUh(a.Os,-1*(b-a.Rl.OC)*BUh(a.Os),c)||HUh(a);CUh(a.Os,b,a.iS.rda(),!0)};HUh=function(a){if(a.Rl.ZEb!==null){var b=a.Rl.ZEb;a.Rl.ZEb=null;a.r_b(b);JUh(a,b);AUh(a.Os,0,!1)}};
LUh=function(a,b){tUh(a.Os,b,()=>{var c;(c=FUh(a))==null||iUh(c)});wUh(a.Os,b,c=>{HUh(a);IUh(a,c,_.QFd)});xUh(a.Os,c=>{HUh(a);IUh(a,c,_.QFd)});_.RFd&&(uUh(a.Os,b,c=>{if(!a.Rl.G1c&&a.pka){var d=c.touches[0];if(!(a.Rl.ZEb===null||d.clientX<16||d.clientX>window.innerWidth-16||KUh(a,d))){var e=zUh(a.Os);e=a.Rl.OC-e/BUh(a.Os);HUh(a);e=(a.Rl.OC-e)*BUh(a.Os);a.Rl.l1b=d.clientX-e;a.Rl.D1c=d.clientY;a.Rl.B_a=d.identifier;a.Rl.n1b=0;a.Rl.Nkc=e;a.Rl.Okc=Number.NEGATIVE_INFINITY;a.Rl.iO=1}if(a.Rl.B_a===null){var f=
c.touches[0];a.Rl.l1b=f.clientX;a.Rl.D1c=f.clientY;a.Rl.B_a=f.identifier;a.Rl.n1b=0;a.Rl.Nkc=0;a.Rl.Okc=c.timeStamp;if(f.clientX<16||f.clientX>window.innerWidth-16)a.Rl.iO=3;a.Rl.iO===0&&KUh(a,f)&&(a.Rl.iO=2)}else if(a.Rl.iO!==2){for(var g of c.changedTouches)if(g.identifier===a.Rl.B_a){f=g;break}if(f){if(a.Rl.iO===0){d=Math.abs(f.clientX-a.Rl.l1b);g=Math.abs(f.clientY-a.Rl.D1c);e=2;let h=g;d/g>1.5&&(e=1,h=d);a.Rl.iO=h>6?e:0}a.Rl.iO!==0&&a.Rl.iO!==1||c.type!=="touchmove"||(c.stopPropagation(),a.Rl.nSc>
0&&c.cancelable&&c.preventDefault());a.Rl.iO===1&&(f=f.clientX-a.Rl.l1b,AUh(a.Os,f,!1),a.Rl.n1b=(f-a.Rl.Nkc)/(c.timeStamp-a.Rl.Okc),a.Rl.Nkc=f,a.Rl.Okc=c.timeStamp,f=a.Rl.OC-f/BUh(a.Os),JUh(a,f),CUh(a.Os,f,a.iS.rda()))}}c.type==="touchmove"&&a.Rl.nSc++}}),vUh(a.Os,b,c=>{if(a.Rl.B_a!==null)if(c.touches.length>0){var d=c.touches[0];for(let e of c.changedTouches)if(e.identifier===a.Rl.B_a){a.Rl.B_a=d.identifier;break}}else a.Rl.B_a=null,a.Rl.iO===1&&(c=c.changedTouches[0].clientX-a.Rl.l1b,d=Math.sign(c),
IUh(a,(Math.abs(c)>a.Os.Aa/4?a.Rl.n1b*d>-.2:a.Rl.n1b*d>.2)?-1*d:0,!0)),a.Rl.iO=0,a.Rl.nSc=0}));yUh(a.Os,b,c=>{c.target===a.Os.Os&&HUh(a)})};PUh=function(a,{index:b,CB:c,initialState:d,Jx:e,yIe:f}){var g=a.Rl.OC===b,h=c?Promise.resolve(c):a.nOb(b);b=new oUh(a.Ub,()=>void a.yT(),b,h,a.iS,a.pka,g,g,MUh(a),f);c&&(b.YLc(b,c),b.Ag=3);a.Gca.add(b);kUh(b,a.pka);lUh(b,g);mUh(b,g);NUh(a,b);DUh(a.Os,b);iUh(b);b.Ii(d,e);OUh(a);return b};
QUh=function(a,b){if(!(a.Gca.get(b)||b<0||b>=a.iS.rda())){qUh(a.Gca,b,d=>{a.Alc(d)});var c=Math.abs(b-a.Rl.OC)===1;PUh(a,{index:b,initialState:b===a.Rl.OC||a.QCb&&c?7:5})}};OUh=function(a){for(let b of a.Gca.getAll())b.reposition(b.index-a.Rl.OC,BUh(a.Os))};RUh=function(a){a.Rl.B_a=null;a.Rl.ZEb=null;AUh(a.Os,0,!1);CUh(a.Os,a.Rl.OC,a.iS.rda());JUh(a,a.Rl.OC)};
SUh=function(a,b){try{let c,d,e=(d=(c=a.iS).Zje)==null?void 0:d.call(c,a.Rl.OC);e&&(e.av=b,document.dispatchEvent(new CustomEvent("viewerUpdated",{detail:e})))}catch(c){}};TUh=function(a,b){var c=b===a.Rl.OC;(b=a.Gca.get(b))&&b.Ca!==c&&(mUh(b,c),c?(a=a.ame(),b.Ii(7,a)):a.QCb||b.Ii(5))};MUh=function(a){return new VTh(_.lFd?a.Uz:b=>{b.dispatch()})};
NUh=function(a,b){{var c=a.Gca;let f=_.oba(c.array,OTh,b.index);if(f>=0){let g;c=(g=c.array[f+1])!=null?g:null}else{var d;c=(d=c.array[-f-1])!=null?d:null}}d=c;var e;a.Os.Os.insertBefore(b.hJ,(e=d==null?void 0:d.hJ)!=null?e:null)};GUh=function(a,b){a=a.iS.rda()-1;return Math.round(Math.max(0,Math.min(b,a)))};
KUh=function(a,b){b=b.target;for(var c;b&&b!==((c=a.Os)==null?void 0:c.Os);){a:{var d=a;var e=b,f=d.ONc.get(e);if(f!==void 0){d=f;break a}b:{f=e;if(f.getAttribute("aria-roledescription")==="slideshow"){f=!0;break b}let g=getComputedStyle(f);f=(g.overflowX==="scroll"||g.overflowX==="auto")&&f.scrollWidth>f.clientWidth}d.ONc.set(e,f);d=f}if(d)return!0;b=b.parentElement}return!1};JUh=function(a,b){b=GUh(a,b);if(b!==a.Rl.vAb){var c=a.Gca.get(b);c&&(c.Ba(Math.sign(b-a.Rl.vAb)),a.Rl.vAb=b)}};
_.UUh=class{constructor(a,b,c,d,e,f,g){this.Uo=a;this.Ub=b;this.iS=c;this.gsd=d;this.fsd=e;this.QCb=f;this.qAa=g;this.ame=()=>new _.tSh;this.Gca=new rUh;this.Rl={OC:0,ZEb:null,l1b:-1,D1c:-1,B_a:null,nSc:0,iO:0,n1b:0,Nkc:0,Okc:Number.NEGATIVE_INFINITY,vAb:-1,G1c:!1};this.DBc=this.pka=!1;this.ONc=new WeakMap;this.Rl.OC=d;this.Rl.vAb=d}wed(a,b,c){this.Mc=a;this.AVc=b;this.eSb=c}getType(){return 3}d4a(){var a,b,c;return((a=FUh(this))==null?void 0:(b=hUh(a))==null?void 0:(c=b.d4a)==null?void 0:c.call(b))||
null}VB({Gl:a,signal:b,Uz:c}){this.Gca.yk();this.Uz=c;b.addEventListener("abort",()=>void this.dispose(),{once:!0});var d=a.querySelector('[jsname="lHGsle"]');this.Os=new EUh(this.Uo,_.mFd?this.qAa:void 0,d!=null?d:void 0);sUh(this.Os,b,a,c);CUh(this.Os,this.Rl.OC,this.iS.rda());a=this.Os.Os.querySelector('[jsname="Qzjw6d"]');a=PUh(this,{index:this.Rl.OC,CB:this.fsd,initialState:5,yIe:a!=null?a:void 0});nUh(a,this.Os.Os.dataset.ved);this.Os.Ca.promise.then(()=>{LUh(this,b)}).catch(()=>{});_.Sg(this.iS.yCd(),
"L6fTBf",()=>{this.iS.scan();QUh(this,this.Rl.OC-1);QUh(this,this.Rl.OC+1)});_.Sg(this.Os.Os,"CdDuO",_.Rn(()=>{this.ONc=new WeakMap;OUh(this);RUh(this)},100));return{status:a.Ha}}async fetch(){var a=(0,_.Wf)(),b=a();a=a(1);try{this.Gca.yk();let c=FUh(this);c.Ii(6);this.pka&&SUh(this,!1);a(await b(c.M8))}finally{b()}}async render(){var a=(0,_.Wf)(),b=a();a=a(1);try{this.Gca.yk();let c=FUh(this).Ii(7);a(await b(this.Os.Ca.promise));this.pka?(QUh(this,this.Rl.OC-1),QUh(this,this.Rl.OC+1)):this.DBc=!0;
a(await b(c))}finally{b()}}setActive(a){a&&this.DBc&&(this.DBc=!1,QUh(this,this.Rl.OC-1),QUh(this,this.Rl.OC+1));this.pka=a;for(let b of this.Gca.getAll())kUh(b,a);a&&SUh(this,!1);a||RUh(this)}serialize(){var a,b,c,d,e=new _.VRh,f=(b=(a=this.iS).getType)==null?void 0:b.call(a);a=_.Yh(e,6,f);b=(d=(c=this.iS).serialize)==null?void 0:d.call(c,this.Rl.OC);c=_.qk(a,5,b);c=_.Zh(c,7,this.QCb);c=_.Fb(c,_.wS,9,this.qAa);var g,h;d=(h=(g=FUh(this))==null?void 0:hUh(g))!=null?h:this.Rl.OC===this.gsd?this.fsd:
null;if(d==null?0:d.serialize)g=d.getType(),g=_.Yh(c,4,g),_.URh(g,d.serialize());return(0,_.YRh)(c)}Hfb(){var a;return(a=FUh(this))==null?void 0:a.Hfb()}T5(){var a;return(a=FUh(this))==null?void 0:a.T5()}i4a(){var a;return(a=FUh(this))==null?void 0:a.i4a()}I4a(a){var b,c;return(b=FUh(this))==null?void 0:(c=b.I4a)==null?void 0:c.call(b,a)}Gfb(a){var b,c;return(b=FUh(this))==null?void 0:(c=b.Gfb)==null?void 0:c.call(b,a)}OOa(){for(let a of this.Gca.getAll())a.OOa()}bXb(a){RUh(this);this.Rl.G1c=!0;var b;
return((b=FUh(this))==null?void 0:b.bXb(a))||!1}Cjc(a){this.Rl.G1c=!1;var b;return((b=FUh(this))==null?void 0:b.Cjc(a))||!1}jCb(a){var b;(b=FUh(this))==null||b.jCb(a)}yT(){if(this.Os.isInstalled()){let a=this.serialize(),b,c,d=(c=(b=this.iS).cwb)==null?void 0:c.call(b,this.Rl.OC);this.Os.yT({content:a,entrypoint:d})}}nOb(a){var b=0;a>this.Rl.OC?b=2:a<this.Rl.OC&&(b=1);if(this.AVc){let c,d,e=(d=(c=this.iS).cwb)==null?void 0:d.call(c,a),f,g=Number((f=e==null?void 0:e.getAttribute("data-sv-cpt"))!=null?
f:"0");if(g>0){let h,k,l=(k=(h=this.iS).cwb)==null?void 0:k.call(h,this.gsd);if(e&&l&&this.eSb&&this.Mc)return this.AVc(g,this.Mc).then(n=>{if(n==null?0:n.A2a)return n.A2a(e,l,this.eSb,this.AVc,{source:b,index:a,count:this.iS.rda()});throw Error("ep`"+a+"`"+g+"`"+e+"`"+e+"`"+this.eSb);}).catch(n=>{throw Error("fp`"+a+"`"+g+"`"+e+"`"+e+"`"+this.eSb+"`"+n);});throw Error("gp`"+a+"`"+g+"`"+e+"`"+e+"`"+this.eSb);}}return this.iS.nOb(a,b)}Alc(a){a.OOa();this.Gca.remove(a.index);var b=this.Os;b.oa&&_.Wg(b.oa,
"CZRWp",{TQ:a.index,Tcd:a.Oi});a.hJ.remove();a.dispose()}r_b(a){var b=this.Rl.OC;this.Rl.OC=a;if(this.Rl.OC!==b){QUh(this,a-1);QUh(this,a+1);TUh(this,a);TUh(this,b);SUh(this,!0);QUh(this,this.Rl.OC);a=FUh(this);a==null||lUh(a,!0);var c;(c=this.Gca.get(b))==null||lUh(c,!1);b=Math.sign(this.Rl.OC-b);this.Rl.OC!==this.Rl.vAb&&(a==null||a.Ba(b),this.Rl.vAb=this.Rl.OC);this.yT();OUh(this)}}dispose(){for(;this.Gca.yk()>0;)this.Alc(pUh(this.Gca));var a,b;(b=(a=this.iS).dispose)==null||b.call(a)}};
VUh={scan(){return 0},nOb(a){throw Error("hp`"+a);},ubc(){return 0},rda(){return 0},yCd(){return document.createElement("div")}};var PTh={[1]:_.MRh};var WUh,XUh;WUh=async function(a,b,c){var d=(0,_.Wf)(),e=d();d=d(1);try{return _.Lk(b,3)&&_.Mk(b,4)?await d(await e(c(_.Dj(b,4),a.Vn()))).kA(_.Ib(_.ij(b,3)),c):null}finally{e()}};XUh=async function(a,b){var c=(0,_.Wf)(),d=c();c=c(1);try{if(!_.Mk(b,6)||!_.Lk(b,5))return VUh;try{let e=c(await d(QTh(_.Dj(b,6),a.Vn())));return c(await d(e.kA(_.Ib(_.ij(b,5)))))}catch(e){return c(),VUh}}finally{d()}};
_.YUh=class extends _.yo{static Ta(){return{service:{Uo:_.Lx,Ub:_.Wu}}}constructor(a){super();this.Uo=a.service.Uo;this.Ub=a.service.Ub}async getInstance({index:a,Ihb:b,iS:c,QCb:d,qAa:e,JR:f}){var g=(0,_.Wf)(),h=g();g=g(1);try{_.mFd&&_.MFd&&!e&&f===1&&(e=_.STh(2));var k=this.Uo,l=this.Ub;if(b!=null)var n=b;else{if(a<0||a>=c.rda())throw Error("ip");var q=c.nOb(a);n=g(await h(q))}return new _.UUh(k,l,c,a,n,d,e)}finally{h()}}async kA(a,b){var c=(0,_.Wf)(),d=c();c=c(1);try{let e=(0,_.XRh)(a),[f,g]=c(await d(Promise.all([WUh(this,
e,b),XUh(this,e)])));return this.getInstance({index:g.ubc(),Ihb:f!=null?f:void 0,iS:g,QCb:_.B(e,7),qAa:_.p(e,_.wS,9),JR:_.Dj(e,10)})}finally{d()}}Aa(){}};_.hg(_.MTh,_.YUh);

_.x();
_.nLp=_.y("aw2uhd",[_.Hr,_.K3a,_.MTh,_.e9a,_.xr,_.Cr,_.Tr]);
var kLp;_.lLp=function(a,b,c,d,e){var f=(0,_.vAe)(a)?a.getImage():a,g=(a=f.Rd(_.BS))&&_.gh(a,2),h=a&&_.gh(a,3),k=_.gh(f,2),l=f.jR();f=l?_.gh(l,1):"";var n=l?_.Zj(l,3):"";l=l?_.Zj(l,2):"";if(!g||!h||!k)throw Error("it");b=new Map([["q",b],["imgurl",f],["imgrefurl",h],["docid",g],["tbnid",k],["vet",1],["w",n],["h",l],["hcb","2"]]);_.B(a,10)&&b.set("itg",1);c&&(b.set("ved",c),d&&b.set("ictx",d),e&&b.set("vet",e));return _.yc(kLp,b)};
_.mLp=function(a,b,c,d,e){var f=(a==null?void 0:a.Ma())||"";if(!f){let g,h,k;(a=(h=(g=a.Da())==null?void 0:g.Aa())==null?void 0:(k=h.Rd(_.sK))==null?void 0:k.getImage())&&(f=_.lLp(a,b,c,d,e))}return f};kLp=(0,_.vc)`/imgres`;
_.o1h=!!(_.Ji[35]&1024);_.p1h=!!(_.Ji[35]&2048);_.q1h=!!(_.Ji[35]&4096);_.r1h=!!(_.Ji[35]&8192);_.s1h=!!(_.Ji[35]>>15&1);_.t1h=!!(_.Ji[35]>>16&1);_.u1h=!!(_.Ji[35]>>17&1);_.v1h=!!(_.Ji[35]>>18&1);_.w1h=!!(_.Ji[35]>>19&1);_.x1h=!!(_.Ji[35]>>20&1);_.y1h=!!(_.Ji[35]>>21&1);_.z1h=!!(_.Ji[35]>>22&1);_.A1h=!!(_.Ji[35]>>24&1);_.B1h=!!(_.Ji[35]>>25&1);_.C1h=!!(_.Ji[35]>>26&1);_.D1h=!!(_.Ji[35]>>28&1);_.E1h=!!(_.Ji[35]>>29&1);_.F1h=!!(_.Ji[36]&1);_.G1h=!!(_.Ji[36]&2);_.H1h=!!(_.Ji[36]&4);
_.I1h=!!(_.Ji[36]&8);_.J1h=!!(_.Ji[36]&16);_.K1h=!!(_.Ji[36]&32);_.L1h=!!(_.Ji[36]&64);_.M1h=!!(_.Ji[36]&128);_.N1h=!!(_.Ji[36]&256);_.O1h=!!(_.Ji[36]&1024);_.P1h=!!(_.Ji[36]&2048);_.Q1h=!!(_.Ji[36]>>14&1);_.R1h=!!(_.Ji[36]>>17&1);_.S1h=!!(_.Ji[36]>>18&1);_.T1h=!!(_.Ji[36]>>20&1);_.U1h=!!(_.Ji[36]>>21&1);_.V1h=!!(_.Ji[36]>>22&1);_.W1h=!!(_.Ji[36]>>23&1);_.X1h=!!(_.Ji[36]>>24&1);_.Y1h=!!(_.Ji[36]>>25&1);_.Z1h=!!(_.Ji[36]>>26&1);_.$1h=!!(_.Ji[36]>>27&1);_.a2h=!!(_.Ji[36]>>28&1);
_.b2h=!!(_.Ji[36]>>29&1);_.c2h=!!(_.Ji[37]&1);_.d2h=!!(_.Ji[37]&2);_.e2h=!!(_.Ji[37]&4);_.f2h=!!(_.Ji[37]&8);_.g2h=!!(_.Ji[37]&16);_.h2h=!!(_.Ji[37]&64);_.i2h=!!(_.Ji[37]&128);_.j2h=!!(_.Ji[37]&256);
_.fFb=!!(_.Ji[41]>>18&1);_.gFb=!!(_.Ji[41]>>19&1);_.hFb=!!(_.Ji[41]>>24&1);
_.v("aw2uhd");
var rLp=function(...a){var b=new Map;a.forEach(c=>{if(c){let [d,e]=c.split(",");b.set(d,e)}});return b},sLp=!!(_.Ji[41]>>28&1),tLp=!!(_.Ji[41]>>29&1);var uLp=class extends _.m{constructor(a){super(a)}Aa(){return _.p(this,_.wS,1)}};uLp.prototype.rb="pwtiR";var wLp,vLp;
wLp=async function(a,b){var c=(0,_.Wf)(),d=c();c=c(1);try{let N=_.ERh(a.getRoot().el()),P=c(await d(a.xsa({index:N==null?void 0:_.LRh(N,a.getRoot().el()),count:N==null?void 0:N.rda()})));if(P){if(N){var e=a.Lva.getInstance({index:_.LRh(N,a.getRoot().el()),Ihb:P,iS:N,qAa:vLp()});var f=c(await d(e))}else f=P;var g=_.yD(a.getRoot().el().parentElement),h=_.pUd.Px();(_.a2h||_.$1h)&&_.SMd(_.RMd(_.QMd(_.PMd(h,2)),2));var k=a.Hh,l=k.showViewer,n=a.getRoot().el(),q=a.Rld(),r=_.pLp(_.sm(a.getData("epType"),""),
b),t=new uLp,A=vLp();var E=_.Fb(t,_.wS,1,A);c(await d(l.call(k,{haa:b,entrypoint:n,viewerType:7,interactionVed:g,gA:q,CB:f,Jx:r,YY:h,dL:E,SMb:_.hFb})));var H=a.getData("v").Ob();document.dispatchEvent(new CustomEvent("viewerOpenFinished",{detail:{relatedImgViewer:H}}))}}finally{d()}};vLp=function(){if(_.yFd)return _.STh(_.xFd?2:1)};
_.xLp=class extends _.Cs{static Ta(){return{service:{Jea:_.MG,plugin:_.jLp,E1c:_.YUh,history:_.SDi,navigation:_.ew,Kc:_.Wu,focus:_.Zv},If:{pB:_.pK,Xga:_.wG}}}constructor(a){super(a.Oa);this.Da=!1;this.Ba=b=>{var c=this.getRoot();if(c.el()){var d=this.getRoot().el().id;c.toggleClass("loWRed",d!==null&&b.detail.vhid===d)}};this.Aa=()=>{var b=this.getRoot();b.el()&&b.hasClass("loWRed")&&(b.removeClass("loWRed"),this.ef.QP(b,{preventScroll:!0}))};this.Hh=a.service.Jea;this.oa=a.service.plugin;this.Lva=
a.service.E1c;this.pB=a.If.pB;this.cj=a.service.history;this.hc=a.service.navigation;this.Ub=a.service.Kc;this.ef=a.service.focus;this.pB&&this.oa.prefetch();_.yx&&(document.addEventListener("viewerUpdated",this.Ba),document.addEventListener("viewerClosed",this.Aa),this.addOnDisposeCallback(()=>{document.removeEventListener("viewerUpdated",this.Ba);document.removeEventListener("viewerClosed",this.Aa)}))}Tc(a){this.trigger("yu1Hm");try{return wLp(this,_.Dwa(a)+_.Bh),a.event.preventDefault(),a.event.stopPropagation(),
!1}catch(b){}return!0}Rld(){var a=this.pB;if(a&&a.jR()){var b=_.jOh(_.hOh(new _.Vp,a.jR().getUrl()),a.getUniqueId());(a=a.Rd(_.BS))&&_.iOh(b,a.uJ());return b}}async xsa(a){var b=this.getRoot().el(),c=this.pB||void 0;a={entrypoint:b,urlParams:rLp((()=>{var d=_.qm(this.getData("eqld"))||_.qm(this.getData("encodedQld"));return d?`eqld,${d}`:""})()),Nzd:a,pB:c};return this.oa.getInstance(a)}Ea(a){this.pB&&(tLp&&_.gLp(this.oa,this.pB),sLp&&!this.Da&&(this.Da=!0,this.Ca(a)))}Ha(a){this.bwa(a.data,!0)}La(a){this.bwa(a.data,
!1)}bwa(a,b){if(a.Ca()&&a.Ao().wk()){var c,d,e;if(((c=a.Ao())==null?void 0:(d=c.getImage())==null?void 0:d.Aa())===((e=this.pB)==null?void 0:e.getUniqueId())){let f,g;(f=this.pB)!=null&&(g=f.Rd(_.BS))!=null&&_.Zh(g,6,b)}}}async Ca(a){var b=this.getRoot().closest("a").el();if(b){var c=this.getRoot().el().getAttribute("data-ved")||"";a=(a=a.ub.el())?Number(a.getAttribute("data-ictx"))||void 0:void 0;var d=c&&_.yXa(c)||void 0;this.pB&&(c=_.lLp(this.pB,_.eo(new _.df(this.cj.getCurrentUrl()),"q")||"",
c,a,d))&&(c=_.lc(c.toString()))&&_.Lc(b,c)}}Ma(a){this.Tc(a);return null}Na(a){a=a.targetElement.el();if(!a)return null;var b=a.getAttribute("href");if(!b)return null;b=_.lc(b);if(!b)return null;this.hc.navigateTo(b);this.Ub.logEvent({Ie:_.Uh(a)});return null}};_.xLp.prototype.$wa$WZxsNc=function(){return this.Na};_.xLp.prototype.$wa$Esn7Cd=function(){return this.Ma};_.xLp.prototype.$wa$hGLEsf=function(){return this.Ca};_.xLp.prototype.$wa$J29LQb=function(){return this.La};
_.xLp.prototype.$wa$hwpOM=function(){return this.Ha};_.xLp.prototype.$wa$UI3Kjd=function(){return this.Ea};_.xLp.prototype.$wa$h5M12e=function(){return this.Tc};_.Es(_.nLp,_.xLp);
_.x();
});
// Google Inc.
