loaded_h_0(function(_){var window=this;
_.rOf=_.y("n7qy6d",[]);
_.lOf=!!(_.Ji[94]>>14&1);_.mOf=!!(_.Ji[94]>>15&1);_.nOf=!!(_.Ji[94]>>16&1);_.oOf=!!(_.Ji[94]>>18&1);_.pOf=!!(_.Ji[94]>>19&1);_.qOf=!!(_.Ji[94]>>20&1);
_.v("n7qy6d");
var sOf=function(){var a="getSelection"in window&&"queryCommandSupported"in document&&"execCommand"in document&&document.queryCommandSupported("copy");if(a)try{a=document.execCommand("copy",!0)}catch(b){a=!1}return a},uOf=function(a){if(a.oa&&a.url){tOf(a);var b=a.url,c=a.Ja("tQ9n1c").el();_.bn(c,b);b=document.createRange();b.selectNodeContents(c);window.getSelection().removeAllRanges();window.getSelection().addRange(b);document.execCommand("copy",!0)&&(a.Aa.hide(),a.Ba.show())}},tOf=function(a){var b=
a.getRoot().el();_.Wg(b,"nVW9lb");a.getRoot().getData("ved").Ob()&&_.Sv(a.getRoot().el())},wOf=class extends _.Cs{constructor(a){super(a.Oa);this.oa=this.url=null;this.Aa=this.Ja("uu7Hed");this.Ca=this.Ja("axr9cd");this.Ba=this.Ja("pAZ6Ed")}updateUrl(a){if(this.url=a){a=this.url;if(vOf){var b=this.Db("zgnjS");b.size()&&(b.el().textContent=a)}else b=this.Db("RYUcpc"),b.size()?(_.Lc(b.el(),a),_.bn(b.el(),a||"")):(b=this.Db("zgnjS"),b.size()&&(_.Io(b,"input").el().value=a));_.jn(this.getRoot().el(),
"visibility",a?"":"hidden");this.Ba.hide();this.Aa.toggle(!!this.oa);this.Ca.toggle(!this.oa)}}setup(){if(this.oa===null){this.oa=sOf();if(vOf)this.getRoot().el().addEventListener("copy",a=>{a.clipboardData&&this.url&&(a.clipboardData.setData("text/plain",this.url),a.preventDefault())});else{let a=this.Db("zgnjS");!this.oa&&a.size()&&(_.Io(a,"input").el().style.cursor="text")}this.Aa.toggle(this.oa);this.Ca.toggle(!this.oa)}}Da(){uOf(this)}Ea(){if(vOf)tOf(this);else{uOf(this);var a=this.Db("zgnjS");
a.size()&&(a=_.Io(a,"input").el(),a.select(),a.focus())}}Ha(){uOf(this)}};wOf.prototype.$wa$RNDhHe=function(){return this.Ha};wOf.prototype.$wa$aiBUrb=function(){return this.Ea};wOf.prototype.$wa$ScPJh=function(){return this.Da};wOf.prototype.$wa$S4w6dd=function(){return this.setup};var vOf=_.oOf;_.Es(_.rOf,wOf);
_.x();
_.xOf=_.y("HPGtmd",[_.xr]);
_.v("HPGtmd");
var yOf,zOf;yOf=function(a,b){return _.lna(new _.df(a),_.GNa(b)).toString()};zOf=function(a,b,c,d,e){var f,g=(f=a.Xm())!=null?f:"",h;f=(h=a.Yt())!=null?h:"";h=a.r3();var k;g=a.Vs(f,g,((k=a.Aa)==null?0:k.Aa())?"\n\n":"\n");var l;if((l=a.xm)==null?0:l.Pa()){let n;g+="\n\n"+((n=a.xm)==null?void 0:n.Na())}d=Object.assign({},d,{body:g});h&&(d[e]=h);b=yOf(b,d);a.iqa(c,b,!_.ji(a.getData("mobile"),!1))};
_.AOf=class extends _.Cs{static Ta(){return{service:{navigation:_.ew}}}constructor(a){super(a.Oa);this.oa=this.Ba=this.Aa=this.xm=null;this.navigation=a.service.navigation;if(this.Ba=this.Ya("GIN7Bd").first())this.oa=this.Gc(this.Ba.el(),_.Vo).then(b=>b)}async setup(){var a=(0,_.Wf)(),b=a();a=a(1);try{this.oa&&a(await b(this.oa)).setup()}finally{b()}}Na(a){var b=yOf("https://www.reddit.com/submit",{url:this.Xm()});this.iqa(a,b,!0)}Ea(a){var b={url:this.Xm()},c=this.Yt();c.length&&(b.text=c);b=yOf("https://www.twitter.com/share",
b);this.iqa(a,b,!0)}Ha(a){var b=this.Yt(),c;b=yOf("https://api.whatsapp.com/send",{text:this.Vs(b,this.Xm(),((c=this.Aa)==null?0:c.Aa())?"\n\n":" ")});this.iqa(a,b,!0)}Da(a){var b=yOf("https://www.facebook.com/sharer/sharer.php",{u:this.Xm()});this.iqa(a,b,!0)}Ca(a){zOf(this,"mailto:",a,{},"subject")}Ma(a){zOf(this,"https://mail.google.com/mail",a,{view:"cm",fs:"1",tf:"1"},"su")}La(){return this.Ja("RgELLe").el()}iqa(a,b,c){c?_.Bo(b,{target:"_blank"}):this.navigation.oa(b);b=this.getRoot().el();_.Wg(b,
"nVW9lb");b=this.getRoot().el();_.Wg(b,"dBhwS");a=a.targetElement;a.getData("ved").Ob()&&_.Sv(a.el())}r3(){return this.xm?this.xm.r3()||this.xm.getTitle()||null:null}Xm(){if(this.xm){let a=this.xm.Da()||this.xm.Ca();if(a)return a}throw Error("om");}Yt(){if(!this.xm)return"";var a;return this.xm.Yt()||(((a=this.Aa)==null?0:a.Ba())?"":this.xm.getTitle())||""}Vs(a,b,c=" "){if(!this.xm)return"";if(a==="")return b;if(b==="")return a;var d;return((d=this.Aa)==null?0:d.Aa())?b+c+a:a+c+b}};
_.AOf.prototype.$wa$nR7Ch=function(){return this.La};_.AOf.prototype.$wa$eOZhO=function(){return this.Ma};_.AOf.prototype.$wa$NmUBTc=function(){return this.Ca};_.AOf.prototype.$wa$rT2OA=function(){return this.Da};_.AOf.prototype.$wa$cmaSVb=function(){return this.Ha};_.AOf.prototype.$wa$re2RZb=function(){return this.Ea};_.AOf.prototype.$wa$ED9Thd=function(){return this.Na};_.AOf.prototype.$wa$S4w6dd=function(){return this.setup};_.Es(_.xOf,_.AOf);
_.x();
_.BOf=_.y("uLYJpc",[_.xOf,_.sr]);
_.v("uLYJpc");
var EOf=async function(a,b){var c=(0,_.Wf)(),d=c();c=c(1);try{let e;(e=a.Ba)==null||e.removeAttr("data-ved");let f;(f=a.Ya("bVp1N").first())==null||f.removeAttr("data-ved");a.Ja("RgELLe").removeAttr("data-ved");a.Ja("P8lkFb").removeAttr("data-ved");a.Db("EcD0F").removeAttr("data-ved");a.xm=b;if(a.oa)c(await d(a.oa)).updateUrl(a.Xm());else return Promise.resolve()}finally{d()}},FOf=async function(a,b){var c=(0,_.Wf)(),d=c();c=c(1);try{b.pBa&&(a.xm.n4b(b.pBa),a.oa&&c(await d(a.oa)).updateUrl(a.Xm()))}finally{d()}},
HOf=async function(a,b){var c=(0,_.Wf)(),d=c();c=c(1);try{try{let e=c(await d(b));c(await d(FOf(a,e)))}catch(e){if(c(),!("function"==typeof GOf&&e instanceof GOf))throw e;}}finally{d()}},GOf=class extends Error{};var IOf=async function(a,b,c){var d=(0,_.Wf)(),e=d();d=d(1);try{if(a.xm=b,d(await e(EOf(a.AYa,b))),c){var f=a.AYa;if(c.Oed){let g;(g=f.Ba)==null||g.setData("ved",c.Oed)}if(c.sId){let g;(g=f.Ya("bVp1N").first())==null||g.setData("ved",c.sId)}c.tId&&f.Ja("RgELLe").setData("ved",c.tId);c.wId&&f.Ja("P8lkFb").setData("ved",c.wId);c.yId&&f.Db("EcD0F").setData("ved",c.yId)}}finally{e()}},KOf=async function(a){var b=(0,_.Wf)(),c=b();b=b(1);try{if(!a.La){if(JOf)if(a.config&&_.rh(a.config,1)){let h=_.u(a.config,
1)||"";a.Sca.Zb(h).show()}else a.Sca.hide();else if(_.rh(a.config,1)){let h=_.u(a.config,1)||"";a.Sca.Zb(h).show();a.Ha.addClass("UrmYj")}else a.Sca.hide(),a.Ha.removeClass("UrmYj");var d=a.AYa,e=!!_.COf(a.config);d.Ja("RgELLe").toggle(!e);var f=a.AYa,g=!!_.DOf(a.config);f.Ja("P8lkFb").toggle(!g);b(await c(a.AYa.setup()));a.La=!0}}finally{c()}},MOf=function(a,b){b.cK.then(()=>{LOf(a,b.event)});return!0},NOf=function(a,b){var c=a.oa.getBoundingClientRect(),d=c.height;if(b.width>0&&b.height>0){if(window.innerHeight-
b.bottom-15>d)d=b.bottom+15;else{var e=b.top-15-d;d=e>0?e:(window.innerHeight-d)/2}b=b.left;e=window.innerWidth-40;b+c.width>e&&(b=e-c.width)}else d=(window.innerHeight-d)/2,b=(window.innerWidth-c.width)/2;a.oa.style.top=`${d}px`;a.oa.style.left=`${b}px`},LOf=function(a,b){a.Aa&&a.Ca&&(a.Aa.classList.remove(a.Ca),a.Ca="");var c=[JOf?a.oa:a.Da];a.Ba&&(c.push(a.Ba),a.Ba=null);_.Rv(c.filter(d=>_.We(d)).map(d=>new _.ko(d,"hide")));a.Aa&&(_.Wg(a.Aa,"tfcxtb",b),a.Aa=null);JOf&&window.removeEventListener("resize",
a.Ea)},OOf=class extends _.Cs{static Ta(){return{controller:{AYa:{jsname:"b0t70b",ctor:_.AOf}},Zc:{Lf:{jsname:"Sx9Kwc",ctor:_.zh}},service:{overlay:_.rv}}}constructor(a){super(a.Oa);this.Ma=this.Ha=this.oa=this.Lf=this.Da=null;this.La=!1;this.Aa=this.xm=this.Ba=null;this.Ca="";this.Ea=()=>{this.close()};this.Oe=a.service.overlay;this.AYa=a.controller.AYa;this.Sca=this.Ja("Sy6N1c");JOf?(this.oa=this.Ja("EvA93").el(),this.addOnDisposeCallback(()=>{window.removeEventListener("resize",this.Ea)})):(this.Ma=
this.Ja("tqp7ud").el(),this.Da=this.Ja("Sx9Kwc").el(),this.Ha=this.Ja("OGvssd"),this.Lf=a.Zc.Lf);this.config=new _.$O}async show(a,b,c,d,e,f){var g=(0,_.Wf)(),h=g();g=g(1);try{let k;d&&(k=f||d.getBoundingClientRect(),e&&(this.Aa=d,this.Ca=e,this.Aa.classList.add(e)));g(await h(IOf(this,a,b)));this.setConfig(c||new _.$O);g(await h(KOf(this)));if(JOf){a=k!=null;let l=_.wv(_.zv(_.Av(new _.Bv,a?0:1),a),n=>MOf(this,n));_.Yo(this,this.oa);g(await h(this.Oe.open(this.oa,l)));a?NOf(this,k):(this.oa.style.top=
"",this.oa.style.left="");window.addEventListener("resize",this.Ea)}else this.Lf.oa(this.Ma);b&&(this.Ba=b.Bxb,g(await h(_.Rv([JOf?this.oa:this.Da,b.Bxb].filter(l=>_.We(l)).map(l=>new _.ko(l,"show"))))))}finally{h()}}async Pa(a,b,c,d,e,f,g){var h=(0,_.Wf)(),k=h();h=h(1);try{let l=c.then(n=>{var q;if(a.Ma()!==((q=this.xm)==null?void 0:q.Ma()))throw new GOf;return n});h(await k(this.show(a,b,d,e,f,g)));h(await k(HOf(this.AYa,l)))}finally{k()}}Na(a){LOf(this,a.event)}close(){JOf?this.Oe.close(this.oa):
this.Lf.close()}stopPropagation(){}setConfig(a){this.config=a;this.La=!1;this.AYa.Aa=a}};OOf.prototype.$wa$mLt3mc=function(){return this.stopPropagation};OOf.prototype.$wa$TvD9Pc=function(){return this.close};OOf.prototype.$wa$SlAvWb=function(){return this.Na};var JOf=_.oOf;_.Es(_.BOf,OOf);
_.x();
});
// Google Inc.
