loaded_h_0(function(_){var window=this;
_.yRb=[2,4];
_.v("p3hmRc");
var ARb,CRb,JRb,HRb;_.DRb=function(){var a,b;zRb!=null||(zRb=Object.freeze({get enabled(){return zRb.cua===-1||_.ji(ARb("iCzhFc"),!1)?!1:zRb.o0e.enabled||zRb.j3c.enabled||zRb.wMe.enabled},environment:ARb("HiPsbb").Ah(BRb,0),B4d:(a=_.qm(ARb("MUE6Ne")))!=null?a:void 0,O1a:(b=_.qm(ARb("cfb2h")))!=null?b:void 0,cua:_.Cd(ARb("yFnxrf"),-1),L$d:_.DJa(ARb("fPDxwd")).map(c=>_.Cd(c,0)).filter(c=>c>0),o0e:CRb("xwAfE",()=>"UUFaWc"),j3c:CRb("xnI9P",()=>"u4g7r"),wMe:CRb("AfY8Hf",()=>"hsFLT")}));return zRb};
ARb=function(a){var b=ERb(a);if(!b.Ob()&&_.da!==_.da.top)try{b=ERb(a,_.da.top)}catch(c){if(!(c instanceof DOMException&&c.name==="SecurityError")){if(c instanceof Error)throw c;throw Error("sf`"+c);}}return b};CRb=function(a,b){a=_.ji(ARb(a),!1);return{enabled:a,Bmc:a?_.xm(ARb(b()),_.FRb).Vd():GRb()}};
JRb=function(a,b){var c=_.QVa();var d=[];var e;c=_.i$a(_.g$a(_.MLb(new _.k$a(a,c),_.NLb(new _.OLb,b.L$d)),(e=b.O1a)!=null?e:""));d&&d.length>0&&HRb(c,d.map(h=>_.jb(h)));switch(a){case 1957:var f=3;break;case 2082:f=2;break;case 1884:f=1;break;case 2649:f=0}var g;return new IRb(c.build(),(g=b.B4d)!=null?g:"",f,b.environment)};HRb=function(a,b){a.Da=b};_.FRb=class extends _.m{constructor(a){super(a)}};var GRb=_.Jb(_.FRb);var BRb={nkf:0,sIf:1,ySf:2,m6e:3,Ztc:4};var zRb,ERb=_.Bd;var IRb=class{constructor(a,b,c,d=0){this.transport=a;this.appName=b;this.oa=c;this.environment=d}},KRb=class{dispatch(){}flush(){}};_.LRb=class extends _.yo{constructor(){super();this.config=_.DRb();this.oa=this.config.enabled?JRb(this.config.cua,this.config):new IRb(new KRb)}};_.hg(_.I$a,_.LRb);
_.x();
_.SRb=[2,3];_.TRb=[1,2];_.URb=[3,4,5];
var PRb;_.ORb=function(a,b){return _.hk(a,2,b)};PRb=function(a,b){Number.isFinite(b)||(b=0);return _.ORb(a.setSeconds(Math.floor(b/1E3)),(b%1E3+1E3)%1E3*1E6)};_.QRb=function(a){var b=new _.nm;return PRb(b,a.getTime())};_.RRb=function(a){return PRb(new _.nm,a)};
_.v("pNBFbe");
var VRb=function(a){var b;return a.TAa+((b=a.Mo)!=null?b:0)},aSb=function(a,b,c,d){a=WRb((new XRb).Sc(a),d);d=_.oj(a,YRb,5,_.URb);d=_.nj(d,ZRb,1);$Rb(d,c).Le(b);return a},bSb=function(a){return _.NRb(new _.cs,a)},cSb=class extends _.m{constructor(a){super(a)}getUrl(){return _.u(this,3)}jd(){return _.rh(this,3)}Aa(a){_.eh(this,5,a)}Ca(a){_.Yh(this,8,a)}Da(a){_.eh(this,10,a)}Ba(a){_.Yh(this,11,a)}},dSb=class extends _.m{constructor(a){super(a)}},eSb=class extends _.m{constructor(a){super(a)}getType(){return _.Dj(this,
1)}setType(a){return _.Yh(this,1,a)}Bf(){return _.Mk(this,1)}yf(){return _.ci(this,1)}getId(){return _.wFa(this,2,_.SRb)}Sc(a){return _.lj(this,2,_.SRb,_.bb(a))}Eh(){var a=_.aj(this,_.SRb,2);return _.Hda(_.Yi(this,a,void 0,void 0,_.cb))!=null}Jf(){return _.BFa(this,2,_.SRb)}},fSb=class extends _.m{constructor(a){super(a)}getStatus(){return _.Dj(this,2)}Pm(){return _.Mk(this,2)}},gSb=class extends _.m{constructor(a){super(a)}},hSb=class extends _.m{constructor(a){super(a)}},$Rb=function(a,b){return _.lk(a,
2,b)},iSb=function(a,b){_.Hfa(a,3,_.Gda,b,_.Hda)},ZRb=class extends _.m{constructor(a){super(a)}getName(){return _.u(this,1)}Le(a){return _.eh(this,1,a)}oh(){return _.rh(this,1)}},YRb=class extends _.m{constructor(a){super(a)}},jSb=function(a,b){_.Yh(a,7,b)},kSb=class extends _.m{constructor(a){super(a)}j6(){return _.Bj(this,2)}setInterval(a){return _.Zh(this,9,a)}clearInterval(){return _.cf(this,9)}},lSb=class extends _.m{constructor(a){super(a)}},WRb=function(a,b){return _.Fb(a,_.cs,2,b)},mSb=function(a){var b=
new lSb;return _.tj(a,4,_.URb,b)},XRb=class extends _.m{constructor(a){super(a)}getId(){return _.Bj(this,1)}Sc(a){return _.lk(this,1,a)}Eh(){return _.Fk(this,1)}Jf(){return _.Yi(this,1,void 0,void 0,_.cb)}},nSb=class extends _.m{constructor(a){super(a)}getId(){return _.Bj(this,1)}Sc(a){return _.nk(this,1,a)}Eh(){return _.Hk(this,1)}Jf(){return _.Yi(this,1,void 0,void 0,_.cb)}getName(){return _.u(this,2)}Le(a){return _.eh(this,2,a)}oh(){return _.rh(this,2)}getStartTime(){return _.p(this,_.nm,4)}Ara(){return _.cf(this,
4)}getDuration(){return _.p(this,_.cs,11)}t5(){return _.cf(this,11)}Nja(){return _.pj(this,_.cs,11)}},oSb=new _.l0a,pSb=new _.l0a;var qSb=Symbol();var rSb=class extends _.m{constructor(a){super(a)}Aa(){return _.nj(this,cSb,5)}Ba(a){_.Fb(this,_.FRb,18,a)}};var sSb=new _.l0a;var tSb=new _.l0a,uSb=new _.l0a;var wSb=class{constructor(a,b){this.oa=a;this.Bmc=b;a=this.Aa.bind(this);if(_.bAa===void 0)throw Error("Id");if(_.bAa)for(let [c,d]of _.bAa)a(c,d);_.cAa.add(a);_.bAa=void 0}Aa(a,b){if(a.q$.length!==1||a.q$[0].Mo!==0){var c=Number;var d=this.Bmc;d=_.af(d,_.aj(d,_.yRb,2));a=(new vSb(a,b,c(d)/1E3)).La;c=new rSb;a=_.Fb(c,nSb,16,a);var e;for(var [,f]of b.entries())c=f,(d=c.get(sSb))&&d.gfd&&(b=a,d=d.gfd.getId(qSb),_.wk(b,19,d)),(b=c.get(pSb))&&(e=b);f=this.Bmc;var g;if((g=e)==null?0:g.oa)g=new _.FRb,e=
_.HFa(g,2,_.yRb,e.Aa),f=_.Yh(e,3,2).Vd();e=this.oa;g=f;f=a.Aa();e.appName!==void 0&&f.Aa(e.appName);f.Ba(e.environment);e.oa&&f.Ca(e.oa);let h,k;(b=(h=_.Yb())==null?void 0:(k=h.Bb)==null?void 0:_.Ina(k.La))&&f.Da(b);a.Ba(g);e.transport.dispatch(a);e.transport.flush()}}},ySb=function(a,b){var c=(0,_.Wf)(1),d=c(),e=c(1);return function*(){e();try{e(yield d(aSb(xSb(a,b.id),b.name,xSb(a,b.parentId),bSb(b.TAa))))}finally{d()}}()},zSb=function(a,b){var c=(0,_.Wf)(1),d=c(),e=c(1);return function*(){e();
try{let f=bSb(b.TAa),g=void 0,h;b.parentId===void 0?(g=a.Da++,h=0):h=xSb(a,b.parentId);if(!b.p1b&&b.parentId!==void 0){g=a.Da++;let r=a.Ca++;e(yield d(aSb(r,_.aAa(b.name,"APGx0e"),h,f)));h=r}let k=xSb(a,b.id),l=WRb((new XRb).Sc(k),f),n=_.oj(l,kSb,3,_.URb);g&&_.lk(n,2,g);$Rb(_.nj(n,ZRb,1),h).Le(b.name);let q=a.extras.get(b.id);if(q){let r=q.get(tSb);r&&jSb(_.eh(n,6,r.oa),r.Aa);let t=q.get(uSb);if(t){let A=Array.from(t.oa,E=>xSb(a,E));iSb(_.nj(n,ZRb,1),A)}}e(yield d(l));b.Mo!==void 0&&e(yield d(mSb(WRb((new XRb).Sc(k),
b.Mo===0?f:bSb(VRb(b))))))}finally{d()}}()},xSb=function(a,b){var c=a.oa[b];c===void 0&&(a.oa[b]=c=a.Ca++);return c},vSb=class{constructor(a,b,c){this.Ha=a;this.extras=b;this.Da=this.Ca=1;this.Ba=Number.POSITIVE_INFINITY;this.Aa=Number.NEGATIVE_INFINITY;this.Ea=Array(a.q$.length).fill(!1);this.oa=Array(a.q$.length);b=(new nSb).Sc(String(a.id));var d=_.RRb(a.startTimeMs);b=_.Fb(b,_.nm,4,d);d=_.nj(b,hSb,10);_.KFa(d,1,_.TRb,c);for(var e of a.q$)this.Ea[e.id]||(this.Ea[e.id]=!0,a=b,c=e.marker?ySb(this,
e):zSb(this,e),_.wj(a,7,XRb,c),this.Ba=Math.min(this.Ba,e.TAa),this.Aa=Math.max(this.Aa,VRb(e)));for(var f of this.extras.values())if((e=f.get(sSb))&&e.O$d.length>0)for(var g of e.O$d)e=new fSb,a=g.gfd.getId(qSb),e=_.yi(e,1,a),e=_.Yh(e,2,g.status),g.status===0?(a=_.Yh(e,2,6),_.Yh(a,3,7)):g.incompleteReason&&_.Yh(e,3,g.incompleteReason),a=_.nj(b,gSb,15),_.wh(a,1,fSb,e);g=void 0;f=[];for(let [k,l]of this.extras.entries()){a=k;e=l.get(oSb);if(!e)continue;c=this.oa[a];a=e.Aa;d=e.oa;g!=null||(g=a);e=f;
a=e.push;var h=new dSb;c=_.lk(h,1,c);c=_.lk(c,2,String(d));a.call(e,c.Vd())}g?(g=(new eSb).setType(2).Sc(String(g)),f=_.uj(g,4,f).Vd()):f=void 0;f&&_.wh(b,8,eSb,f);b.Le(this.Ha.q$[0].name);f=bSb(this.Aa-this.Ba);_.Fb(b,_.cs,11,f);this.La=b.Vd()}isEmpty(){return this.Ha.q$.length===1}};_.hg(_.J$a,class extends _.yo{constructor(a){super();this.config=_.DRb();this.logger=null;this.oa=a.service.RBe.oa}static Ta(){return{service:{RBe:_.LRb}}}init(){this.config.j3c.enabled&&new wSb(this.oa,this.config.j3c.Bmc)}});
_.x();
});
// Google Inc.
