# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /Users/builder/cbouss/perseverance-python-buildout/aggregate/tldextract-feedstock/recipe, last modified Fri Nov 15 11:38:07 2024
# ------------------------------------------------

package:
  name: tldextract
  version: 5.1.2
source:
  sha256: c9e17f756f05afb5abac04fe8f766e7e70f9fe387adb1859f0f52408ee060200
  url: https://pypi.io/packages/source/t/tldextract/tldextract-5.1.2.tar.gz
build:
  entry_points:
    - tldextract = tldextract.cli:main
  number: '0'
  script: /Users/builder/cbouss/perseverance-python-buildout/croot/tldextract_1731746027796/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313hecd8cb5_0
requirements:
  host:
    - bzip2 1.0.8 h6c40b1e_6
    - ca-certificates 2024.9.24 hecd8cb5_0
    - expat 2.6.3 h6d0c2b6_0
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - libmpdec 4.0.0 h46256e1_0
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.15 h46256e1_0
    - packaging 24.1 py313hecd8cb5_0
    - pip 24.2 py313hecd8cb5_0
    - python 3.13.0 h1ec50cd_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 hca72f7f_0
    - setuptools 75.1.0 py313hecd8cb5_0
    - setuptools-scm 8.1.0 py313hecd8cb5_0
    - setuptools_scm 8.1.0 hd3eb1b0_0
    - sqlite 3.45.3 h6c40b1e_0
    - tk 8.6.14 h4d00af3_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py313hecd8cb5_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
  run:
    - filelock >=3.0.8
    - idna
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - requests >=2.1.0
    - requests-file >=1.4
test:
  commands:
    - pip check
    - tldextract --help
    - pytest tests -v --ignore=tests/test_release.py
  imports:
    - tldextract
  requires:
    - pip
    - pytest
    - pytest-mock
    - responses
  source_files:
    - tests
about:
  description: 'tldextract accurately separates a URL''s subdomain, domain, and public
    suffix, using the Public Suffix List (PSL).

    Say you want just the "google" part of https://www.google.com. Everybody gets
    this wrong. Splitting on the "." and taking the 2nd-to-last element only works
    for simple domains, e.g. .com.

    Consider http://forums.bbc.co.uk: the naive splitting method will give you "co"
    as the domain, instead of "bbc".

    Rather than juggle TLDs, gTLDs, or ccTLDs yourself, tldextract extracts the currently
    living public suffixes according to the Public Suffix List.

    A public suffix is also sometimes called an effective TLD (eTLD).

    '
  dev_url: https://github.com/john-kurkowski/tldextract
  doc_url: https://github.com/john-kurkowski/tldextract/blob/master/README.md
  home: https://github.com/john-kurkowski/tldextract
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Accurately separate the TLD from the registered domain andsubdomains of
    a URL, using the Public Suffix List.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jan-janssen
    - pmlandwehr
