.TH HYPERXMP-ADD-BYTECOUNT 1 "22 November 2020" "v1.1"
.SH NAME
hyperxmp-add-bytecount \- adds/updates byteCount specification in XMP
packet in PDF file.
.SH SYNOPSIS
.B hyperxmp-add-bytecount
.RI [ options ]
.IR filename.pdf ...
.SH DESCRIPTION
\fBhyperxmp-add-bytecount\fP adds/updates the \fCbyteCount\fP
specification in the XMP packet in a PDF file(s), with \fCbyteCount\fP
= file size. The XMP packet needs to be of, or compatible with, the
format produced from a document that uses
.UR https://ctan.org/pkg/hyperxmp
the
.ie t L\h'-0.36'\v'-0.15'\s-2A\s+2\v'0.15'\h'-0.15'T\h'-0.1667'\v'0.2'E\v'-0.2'\h'-0.125'X
.el LaTeX
hyperxmp package
.UE .
.PP
If no XMP packet of a compatible form is found in the PDF file, no
change is made to the file.
.SH OPTIONS
.IP \fB-help\fP
Write usage summary and exit.
.IP \fB-version\fP
Output version information and exit.
.SH BUGS
Email bug reports to
.MT jcc8@psu.edu
John Collins
.ME
and/or
.MT scott+hyxmp@pakin.org
Scott Pakin
.ME .
