#
# Makefile rules for the orb package
#
KEXT_NAME = orb
KEXT_SOURCES = src/orb.c

# include shared GAP package build system
GAPPATH = /private/var/tmp/sage-10.8-current/local/lib/gap/
include Makefile.gappkg
